import type { ThemeDefinitionInput } from './schema.ts';

/**
 * Authored theme data. Art direction rules that hold across every theme:
 * danger stays magenta/orange, safe stays cyan/mint, interact stays yellow, so a
 * player who learned one round can read any other at a glance. Everything else
 * (base colours, sky, light temperature, grade) is free to change.
 */

const candy: ThemeDefinitionInput = {
  id: 'candy',
  name: 'Candy Clouds',
  palette: {
    primary: '#ff7ab8',
    secondary: '#8f7bff',
    accent: '#5ce1e6',
    danger: '#ff3d7f',
    safe: '#62f0c0',
    neutral: '#fff1f7',
    interact: '#ffd23f',
    pattern: '#ffffff',
    structure: '#c9b8ff',
    trim: '#ffe3f1',
    ink: '#3a1f4d',
  },
  sky: { top: '#4fa3ff', horizon: '#ffd6f2', bottom: '#bfe8ff', sunDisc: '#fff6d8', sunSize: 1, stars: 0 },
  fog: { color: '#ffdcf0', near: 112, far: 442 },
  sun: { color: '#fff1dc', intensity: 2.6, direction: { x: 0.45, y: 0.8, z: 0.35 } },
  hemisphere: { sky: '#dff1ff', ground: '#ffc9e6', intensity: 1.35 },
  clouds: { tint: '#ffffff', shade: '#f4c6ea', density: 1 },
  decor: {
    set: 'candy',
    colors: ['#ff7ab8', '#8f7bff', '#5ce1e6', '#ffd23f', '#62f0c0', '#ff9a52'],
    balloons: true,
    crowd: true,
  },
  void: { style: 'clouds', color: '#ffe3f4', color2: '#c7b6ff', depth: -28 },
  grade: {
    exposure: 1.02,
    saturation: 1.12,
    contrast: 1.04,
    lift: [0.01, 0, 0.02],
    gamma: [1, 1, 1],
    gain: [1.02, 1, 1.02],
    vignette: 0.22,
  },
  bloom: { strength: 0.77, threshold: 0.32, radius: 0.45 },
  weather: { default: 'clear', allowed: ['clear', 'windy', 'sunset', 'night', 'stormy'], wind: 0.2 },
};

const factory: ThemeDefinitionInput = {
  id: 'factory',
  name: 'Toy Factory',
  palette: {
    primary: '#ffb238',
    secondary: '#4f8cff',
    accent: '#ff5d5d',
    danger: '#ff4a6e',
    safe: '#3fe0d0',
    neutral: '#e9edf5',
    interact: '#ffe03a',
    pattern: '#2d3350',
    structure: '#7c8db5',
    trim: '#d8e1f2',
    ink: '#1f2540',
  },
  sky: { top: '#5f9bd9', horizon: '#ffe2b8', bottom: '#cde4f7', sunDisc: '#fff0c8', sunSize: 0.9, stars: 0 },
  fog: { color: '#f2e2cc', near: 96, far: 391 },
  sun: { color: '#ffe8c4', intensity: 2.5, direction: { x: -0.4, y: 0.75, z: 0.45 } },
  hemisphere: { sky: '#e1ecff', ground: '#e8c79c', intensity: 1.3 },
  clouds: { tint: '#fff8ef', shade: '#d6c2ad', density: 0.7 },
  decor: {
    set: 'factory',
    colors: ['#ffb238', '#4f8cff', '#ff5d5d', '#3fe0d0', '#9c7bff'],
    balloons: true,
    crowd: true,
  },
  void: { style: 'clouds', color: '#f3e6d6', color2: '#a9b8d8', depth: -26 },
  grade: {
    exposure: 1,
    saturation: 1.08,
    contrast: 1.08,
    lift: [0, 0, 0.015],
    gamma: [1, 1, 1],
    gain: [1.03, 1.01, 0.98],
    vignette: 0.28,
  },
  bloom: { strength: 0.66, threshold: 0.33, radius: 0.4 },
  weather: { default: 'clear', allowed: ['clear', 'windy', 'night', 'stormy'], wind: 0.15 },
};

const frosty: ThemeDefinitionInput = {
  id: 'frosty',
  name: 'Frosty Peaks',
  palette: {
    primary: '#9fd8ff',
    secondary: '#ffffff',
    accent: '#b28dff',
    danger: '#ff5a8a',
    safe: '#55f2d8',
    neutral: '#eef7ff',
    interact: '#ffd94a',
    pattern: '#5aa0e6',
    structure: '#b9cfee',
    trim: '#ffffff',
    ink: '#24375c',
  },
  sky: { top: '#6db7ff', horizon: '#e9f5ff', bottom: '#d3ecff', sunDisc: '#ffffff', sunSize: 0.85, stars: 0 },
  fog: { color: '#e4f2ff', near: 88, far: 374 },
  sun: { color: '#eef6ff', intensity: 2.4, direction: { x: 0.3, y: 0.7, z: -0.5 } },
  hemisphere: { sky: '#e6f4ff', ground: '#b9d6f2', intensity: 1.5 },
  clouds: { tint: '#ffffff', shade: '#c4dbf2', density: 1.2 },
  decor: {
    set: 'frosty',
    colors: ['#9fd8ff', '#ffffff', '#b28dff', '#55f2d8', '#ff9fc4'],
    balloons: true,
    crowd: true,
  },
  void: { style: 'clouds', color: '#eef7ff', color2: '#a9cdf0', depth: -30 },
  grade: {
    exposure: 1.02,
    saturation: 1.02,
    contrast: 1.05,
    lift: [0, 0.005, 0.02],
    gamma: [1.01, 1, 0.98],
    gain: [0.98, 1, 1.04],
    vignette: 0.2,
  },
  bloom: { strength: 0.99, threshold: 0.31, radius: 0.5 },
  weather: { default: 'snow', allowed: ['snow', 'clear', 'windy', 'night', 'stormy'], wind: 0.35 },
};

const jungle: ThemeDefinitionInput = {
  id: 'jungle',
  name: 'Jelly Jungle',
  palette: {
    primary: '#6fe08a',
    secondary: '#ffcc4d',
    accent: '#ff7a59',
    danger: '#ff3f7a',
    safe: '#4de8e0',
    neutral: '#f6f1d9',
    interact: '#ffe03d',
    pattern: '#2f8f5b',
    structure: '#b5875c',
    trim: '#ffe9b0',
    ink: '#21391f',
  },
  sky: { top: '#48b4e8', horizon: '#e4ffd6', bottom: '#c9f2e2', sunDisc: '#fffbd6', sunSize: 1.1, stars: 0 },
  fog: { color: '#d9f5d8', near: 80, far: 357 },
  sun: { color: '#fff4cf', intensity: 2.7, direction: { x: 0.5, y: 0.85, z: 0.2 } },
  hemisphere: { sky: '#e0fbe6', ground: '#9fd18a', intensity: 1.3 },
  clouds: { tint: '#ffffff', shade: '#cfe8c8', density: 0.9 },
  decor: {
    set: 'jungle',
    colors: ['#6fe08a', '#ffcc4d', '#ff7a59', '#4de8e0', '#c27bff'],
    balloons: true,
    crowd: true,
  },
  void: { style: 'water', color: '#3fc6c9', color2: '#c9fff1', depth: -24 },
  grade: {
    exposure: 1,
    saturation: 1.15,
    contrast: 1.05,
    lift: [0, 0.01, 0],
    gamma: [1, 1, 1],
    gain: [1.02, 1.03, 0.97],
    vignette: 0.26,
  },
  bloom: { strength: 0.66, threshold: 0.33, radius: 0.45 },
  weather: { default: 'clear', allowed: ['clear', 'windy', 'stormy', 'sunset'], wind: 0.25 },
};

const sunset: ThemeDefinitionInput = {
  id: 'sunset',
  name: 'Sunset Sundae',
  palette: {
    primary: '#ff9a6b',
    secondary: '#c77dff',
    accent: '#ffd36e',
    danger: '#ff2f6d',
    safe: '#5ef2d0',
    neutral: '#fff0e3',
    interact: '#ffe04a',
    pattern: '#fff7ee',
    structure: '#d792b8',
    trim: '#ffd9c2',
    ink: '#3d1b3a',
  },
  sky: {
    top: '#5b5bd6',
    horizon: '#ffb08a',
    bottom: '#ffd9b0',
    sunDisc: '#ffe7a8',
    sunSize: 1.6,
    stars: 0.05,
  },
  fog: { color: '#ffc5a6', near: 96, far: 408 },
  sun: { color: '#ffc58f', intensity: 2.3, direction: { x: -0.75, y: 0.3, z: 0.5 } },
  hemisphere: { sky: '#ffd6c4', ground: '#b77fbf', intensity: 1.25 },
  clouds: { tint: '#ffe0cc', shade: '#d98fb4', density: 1.1 },
  decor: {
    set: 'sunset',
    colors: ['#ff9a6b', '#c77dff', '#ffd36e', '#5ef2d0', '#ff6fb5'],
    balloons: true,
    crowd: true,
  },
  void: { style: 'clouds', color: '#ffc7b5', color2: '#b98ad8', depth: -28 },
  grade: {
    exposure: 1,
    saturation: 1.1,
    contrast: 1.06,
    lift: [0.02, 0, 0.03],
    gamma: [0.98, 1, 1.02],
    gain: [1.05, 0.99, 0.96],
    vignette: 0.3,
  },
  bloom: { strength: 1.1, threshold: 0.3, radius: 0.55 },
  weather: { default: 'sunset', allowed: ['sunset', 'clear', 'windy'], wind: 0.2 },
};

const space: ThemeDefinitionInput = {
  id: 'space',
  name: 'Cosmic Carnival',
  palette: {
    primary: '#8a7bff',
    secondary: '#4fd6ff',
    accent: '#ff9be0',
    danger: '#ff3d8b',
    safe: '#3dffc8',
    neutral: '#dcd8ff',
    interact: '#ffe14d',
    pattern: '#ffffff',
    structure: '#4a4290',
    trim: '#bfb6ff',
    ink: '#120b2e',
  },
  sky: { top: '#0b0730', horizon: '#3b2a8a', bottom: '#1a1250', sunDisc: '#c9f1ff', sunSize: 0.7, stars: 1 },
  fog: { color: '#2a1f66', near: 112, far: 476 },
  sun: { color: '#d6e4ff', intensity: 2.2, direction: { x: 0.35, y: 0.75, z: -0.4 } },
  hemisphere: { sky: '#8f9bff', ground: '#5a2f7a', intensity: 1.2 },
  clouds: { tint: '#9a86ff', shade: '#3a2a80', density: 0.6 },
  decor: {
    set: 'space',
    colors: ['#8a7bff', '#4fd6ff', '#ff9be0', '#3dffc8', '#ffe14d'],
    balloons: false,
    crowd: true,
  },
  void: { style: 'stars', color: '#120b38', color2: '#9a7bff', depth: -30 },
  grade: {
    exposure: 1.05,
    saturation: 1.12,
    contrast: 1.08,
    lift: [0.01, 0, 0.04],
    gamma: [1, 1, 0.97],
    gain: [1, 0.99, 1.05],
    vignette: 0.35,
  },
  bloom: { strength: 1.76, threshold: 0.25, radius: 0.6 },
  weather: { default: 'night', allowed: ['night', 'clear'], wind: 0.05 },
};

const beach: ThemeDefinitionInput = {
  id: 'beach',
  name: 'Splash Shores',
  palette: {
    primary: '#ffd88a',
    secondary: '#ff8fab',
    accent: '#3fc5ff',
    danger: '#ff4f7b',
    safe: '#4ff0d2',
    neutral: '#fff8e8',
    interact: '#ffe23a',
    pattern: '#ffffff',
    structure: '#e8b27a',
    trim: '#fff2d1',
    ink: '#3a2a1c',
  },
  sky: { top: '#2f9cf5', horizon: '#c9f4ff', bottom: '#e1f8ff', sunDisc: '#fffbe0', sunSize: 1.2, stars: 0 },
  fog: { color: '#d4f3ff', near: 112, far: 442 },
  sun: { color: '#fff6dc', intensity: 2.9, direction: { x: 0.25, y: 0.9, z: 0.3 } },
  hemisphere: { sky: '#d7f4ff', ground: '#ffe1b0', intensity: 1.35 },
  clouds: { tint: '#ffffff', shade: '#cfe6f2', density: 0.8 },
  decor: {
    set: 'beach',
    colors: ['#ffd88a', '#ff8fab', '#3fc5ff', '#4ff0d2', '#ffb04a'],
    balloons: true,
    crowd: true,
  },
  void: { style: 'water', color: '#21b4e6', color2: '#e9fbff', depth: -22 },
  grade: {
    exposure: 1.03,
    saturation: 1.1,
    contrast: 1.03,
    lift: [0, 0.005, 0.01],
    gamma: [1, 1, 1],
    gain: [1.02, 1.01, 0.99],
    vignette: 0.2,
  },
  bloom: { strength: 0.66, threshold: 0.33, radius: 0.45 },
  weather: { default: 'clear', allowed: ['clear', 'windy', 'sunset', 'stormy'], wind: 0.3 },
};

const neon: ThemeDefinitionInput = {
  id: 'neon',
  name: 'Neon Nights',
  palette: {
    primary: '#2d2a6b',
    secondary: '#00e5ff',
    accent: '#ff3df2',
    danger: '#ff3d6e',
    safe: '#2bffb8',
    neutral: '#3c3880',
    interact: '#ffe62e',
    pattern: '#00e5ff',
    structure: '#1d1a4a',
    trim: '#8f7bff',
    ink: '#07051a',
  },
  sky: {
    top: '#090522',
    horizon: '#5a1f8f',
    bottom: '#1b0d45',
    sunDisc: '#ff7ae6',
    sunSize: 1.4,
    stars: 0.8,
  },
  fog: { color: '#2b1260', near: 88, far: 391 },
  sun: { color: '#c7b2ff', intensity: 1.6, direction: { x: -0.3, y: 0.6, z: 0.55 } },
  hemisphere: { sky: '#6a5cff', ground: '#ff3df2', intensity: 0.9 },
  clouds: { tint: '#7a4ad0', shade: '#2a1260', density: 0.5 },
  decor: {
    set: 'neon',
    colors: ['#00e5ff', '#ff3df2', '#2bffb8', '#ffe62e', '#8f7bff'],
    balloons: true,
    crowd: true,
  },
  void: { style: 'stars', color: '#0d0630', color2: '#ff3df2', depth: -26 },
  grade: {
    exposure: 1.05,
    saturation: 1.2,
    contrast: 1.12,
    lift: [0.01, 0, 0.03],
    gamma: [1, 1, 1],
    gain: [1.02, 0.98, 1.05],
    vignette: 0.38,
  },
  bloom: { strength: 1.5, threshold: 0.3, radius: 0.6 },
  weather: { default: 'night', allowed: ['night', 'stormy'], wind: 0.1 },
};

const castle: ThemeDefinitionInput = {
  id: 'castle',
  name: 'Bouncy Castle Keep',
  palette: {
    primary: '#b9a6ff',
    secondary: '#ffc857',
    accent: '#ff7eb6',
    danger: '#ff4b6b',
    safe: '#5ff0cf',
    neutral: '#f3eee6',
    interact: '#ffdf3b',
    pattern: '#7a5fd1',
    structure: '#a7a0b8',
    trim: '#fff3d6',
    ink: '#2b2240',
  },
  sky: { top: '#6c9cff', horizon: '#ffe7d1', bottom: '#d6e6ff', sunDisc: '#fff4d4', sunSize: 1, stars: 0 },
  fog: { color: '#eedff0', near: 96, far: 408 },
  sun: { color: '#fff0d6', intensity: 2.5, direction: { x: 0.55, y: 0.7, z: -0.3 } },
  hemisphere: { sky: '#e3e8ff', ground: '#d8c3a5', intensity: 1.3 },
  clouds: { tint: '#ffffff', shade: '#dccbe8', density: 1 },
  decor: {
    set: 'castle',
    colors: ['#b9a6ff', '#ffc857', '#ff7eb6', '#5ff0cf', '#7ab8ff'],
    balloons: true,
    crowd: true,
  },
  void: { style: 'clouds', color: '#f0e6f6', color2: '#b6a8e6', depth: -28 },
  grade: {
    exposure: 1,
    saturation: 1.06,
    contrast: 1.06,
    lift: [0.01, 0, 0.015],
    gamma: [1, 1, 1],
    gain: [1.02, 1, 0.99],
    vignette: 0.26,
  },
  bloom: { strength: 0.7, threshold: 0.33, radius: 0.45 },
  weather: { default: 'clear', allowed: ['clear', 'night', 'stormy', 'windy', 'sunset'], wind: 0.2 },
};

const goo: ThemeDefinitionInput = {
  id: 'goo',
  name: 'Gloop Lagoon',
  palette: {
    primary: '#b98cff',
    secondary: '#7cf27c',
    accent: '#ffb347',
    danger: '#ff3f8e',
    safe: '#45f0e0',
    neutral: '#f1ecff',
    interact: '#ffe03a',
    pattern: '#ffffff',
    structure: '#7d63c4',
    trim: '#e0d2ff',
    ink: '#24123f',
  },
  sky: { top: '#6a7cff', horizon: '#ffd2f0', bottom: '#d2c6ff', sunDisc: '#fff2e0', sunSize: 1, stars: 0 },
  fog: { color: '#e2d2ff', near: 88, far: 374 },
  sun: { color: '#fff0e6', intensity: 2.4, direction: { x: -0.35, y: 0.8, z: -0.35 } },
  hemisphere: { sky: '#ece2ff', ground: '#9ee6a0', intensity: 1.3 },
  clouds: { tint: '#ffffff', shade: '#d9c4f0', density: 0.9 },
  decor: {
    set: 'goo',
    colors: ['#b98cff', '#7cf27c', '#ffb347', '#45f0e0', '#ff7ab8'],
    balloons: true,
    crowd: true,
  },
  void: { style: 'slime', color: '#ff4fa8', color2: '#ffd0ec', depth: -14 },
  grade: {
    exposure: 1,
    saturation: 1.12,
    contrast: 1.05,
    lift: [0.01, 0, 0.02],
    gamma: [1, 1, 1],
    gain: [1.01, 1.02, 1.01],
    vignette: 0.27,
  },
  bloom: { strength: 0.99, threshold: 0.3, radius: 0.5 },
  weather: { default: 'clear', allowed: ['clear', 'stormy', 'night', 'sunset'], wind: 0.15 },
};

/** Every authored theme, unvalidated. Validated once by `index.ts`. */
export const THEME_INPUTS: readonly ThemeDefinitionInput[] = [
  candy,
  factory,
  frosty,
  jungle,
  sunset,
  space,
  beach,
  neon,
  castle,
  goo,
];
