/**
 * The item shop collection: original `store` cosmetics sold for Gumballs (and
 * Gems at Legendary/Mythic), grouped into themed sets that the store also
 * sells as discounted bundles.
 *
 * Every entry reuses render parameters the Tumbler already supports — existing
 * accessory meshes in new tints, existing shader patterns at new scales and
 * angles, existing face parameters, animation clips, VFX kinds and footstep
 * packs — so no item here needs new art to render.
 */
import { itemMeta } from './pricing.ts';
import type { CosmeticItemInput, Rarity } from './schema.ts';

const store = (rarity: Rarity): ReturnType<typeof itemMeta> => itemMeta(rarity, 'store');

// -----------------------------------------------------------------------------
// Skins
// -----------------------------------------------------------------------------

const skins: CosmeticItemInput[] = [
  {
    id: 'color.arcade-neon',
    slot: 'color',
    name: 'Arcade Neon',
    description: 'Glowing cabinet colours from the back of the arcade.',
    colors: ['#1e1530', '#3bf0ff', '#ff3bd4'],
    ...store('rare'),
  },
  {
    id: 'color.rose-garden',
    slot: 'color',
    name: 'Rose Garden',
    description: 'Petal pink with a fresh green stem.',
    colors: ['#ff7aa8', '#5fd16b', '#fff3f7'],
    ...store('uncommon'),
  },
  {
    id: 'color.abyss',
    slot: 'color',
    name: 'Abyss Blue',
    description: 'Deep-sea navy with a bioluminescent glow.',
    colors: ['#1b3a6b', '#3fd0c9', '#ff7a7a'],
    ...store('rare'),
  },
  {
    id: 'color.frostbite',
    slot: 'color',
    name: 'Frostbite',
    description: 'Icy blue and snowy white. Bring mittens.',
    colors: ['#a8e1ff', '#ffffff', '#3f7fd8'],
    ...store('uncommon'),
  },
  {
    id: 'color.moon-dust',
    slot: 'color',
    name: 'Moon Dust',
    description: 'Silvery grey with a hint of crater purple.',
    colors: ['#c7cede', '#7c5cff', '#2a2238'],
    ...store('epic'),
  },
  {
    id: 'color.bubble-tea',
    slot: 'color',
    name: 'Bubble Tea',
    description: 'Milky caramel with chewy tapioca pearls.',
    colors: ['#e8c39e', '#3b2a22', '#fff8ee'],
    ...store('common'),
  },
  {
    id: 'color.lava-lamp',
    slot: 'color',
    name: 'Lava Lamp',
    description: 'Groovy orange blobs on a purple glow.',
    colors: ['#ff6a2b', '#9b5cff', '#ffd23f'],
    ...store('epic'),
  },
  {
    id: 'color.mango',
    slot: 'color',
    name: 'Mango Tango',
    description: 'Ripe mango with a lime twist.',
    colors: ['#ffb000', '#b6ff3b', '#fff1c9'],
    ...store('common'),
  },
  {
    id: 'color.forest',
    slot: 'color',
    name: 'Forest Floor',
    description: 'Mossy green, bark brown and a mushroom cap.',
    colors: ['#3f8f4a', '#8a5a3c', '#ff5a6e'],
    ...store('uncommon'),
  },
  {
    id: 'color.golden-hour',
    slot: 'color',
    name: 'Golden Hour',
    description: 'That perfect sunset glow, bottled.',
    colors: ['#ffc94a', '#ff7a59', '#fff3c4'],
    ...store('legendary'),
  },
];

const patterns: CosmeticItemInput[] = [
  {
    id: 'pattern.pixel-grid',
    slot: 'pattern',
    name: 'Pixel Grid',
    description: 'Tiny squares straight out of an 8-bit game.',
    pattern: 'checker',
    scale: 0.4,
    ...store('uncommon'),
  },
  {
    id: 'pattern.tide',
    slot: 'pattern',
    name: 'High Tide',
    description: 'Gentle rolling waves, slightly tilted.',
    pattern: 'waves',
    scale: 1.2,
    angle: 15,
    ...store('uncommon'),
  },
  {
    id: 'pattern.starfield',
    slot: 'pattern',
    name: 'Deep Space',
    description: 'A dense starfield for long-haul tumbling.',
    pattern: 'galaxy',
    scale: 1.3,
    ...store('epic'),
  },
  {
    id: 'pattern.freckle-dots',
    slot: 'pattern',
    name: 'Freckle Dots',
    description: 'A light scatter of tiny dots.',
    pattern: 'dots',
    scale: 1.6,
    ...store('common'),
  },
  {
    id: 'pattern.racing',
    slot: 'pattern',
    name: 'Racing Stripes',
    description: 'Bold vertical stripes. Adds zero speed. Looks fast.',
    pattern: 'stripes',
    scale: 0.7,
    angle: 90,
    ...store('common'),
  },
  {
    id: 'pattern.wild-spots',
    slot: 'pattern',
    name: 'Wild Spots',
    description: 'Big-cat spots for the jungle rounds.',
    pattern: 'spots',
    scale: 0.8,
    ...store('rare'),
  },
  {
    id: 'pattern.tartan',
    slot: 'pattern',
    name: 'Highland Tartan',
    description: 'A tight weave for windy summits.',
    pattern: 'plaid',
    scale: 1.4,
    ...store('rare'),
  },
  {
    id: 'pattern.big-hearts',
    slot: 'pattern',
    name: 'Big Hearts',
    description: 'Fewer hearts. Much bigger hearts.',
    pattern: 'hearts',
    scale: 0.7,
    ...store('uncommon'),
  },
  {
    id: 'pattern.lightning',
    slot: 'pattern',
    name: 'Lightning Bolt',
    description: 'Electric zigzags on the diagonal.',
    pattern: 'zigzag',
    scale: 0.6,
    angle: 45,
    ...store('rare'),
  },
  {
    id: 'pattern.dizzy-spiral',
    slot: 'pattern',
    name: 'Dizzy Spiral',
    description: 'A tight spiral that never stops turning.',
    pattern: 'swirl',
    scale: 1.5,
    ...store('epic'),
  },
];

// -----------------------------------------------------------------------------
// Faces
// -----------------------------------------------------------------------------

const faces: CosmeticItemInput[] = [
  {
    id: 'face.arcade-shades',
    slot: 'face',
    name: 'Arcade Shades',
    description: 'Cyan star shades for the high-score table.',
    face: { accessory: 'star-shades', tint: ['#3bf0ff'] },
    ...store('epic'),
  },
  {
    id: 'face.night-owl',
    slot: 'face',
    name: 'Night Owl',
    description: 'Big amber eyes, a little heavy-lidded.',
    face: { lidRest: 0.3, iris: '#ffb02e', eyeScale: 1.2 },
    ...store('uncommon'),
  },
  {
    id: 'face.crush',
    slot: 'face',
    name: 'Crush Mode',
    description: 'Magenta heart eyes and fluttering lashes.',
    face: { pupil: 'heart', iris: '#ff4fd8', lashes: true, eyeScale: 1.1 },
    ...store('rare'),
  },
  {
    id: 'face.garden-specs',
    slot: 'face',
    name: 'Gardener Specs',
    description: 'Leafy green frames for spotting ladybugs.',
    face: { accessory: 'glasses', tint: ['#2fbf71'], freckles: true },
    ...store('uncommon'),
  },
  {
    id: 'face.astro-visor',
    slot: 'face',
    name: 'Astro Visor',
    description: 'A mirrored helmet visor for zero-gravity rounds.',
    face: { accessory: 'visor', tint: ['#7cf2ff'] },
    ...store('rare'),
  },
  {
    id: 'face.walrus',
    slot: 'face',
    name: 'Walrus Whiskers',
    description: 'A bushy snow-white mustache.',
    face: { accessory: 'mustache', tint: ['#f5f0e6'], lidRest: 0.2 },
    ...store('rare'),
  },
  {
    id: 'face.freckle-kitty',
    slot: 'face',
    name: 'Freckle Kitty',
    description: 'Cat eyes and a dusting of freckles.',
    face: { pupil: 'cat', iris: '#ff8a3d', freckles: true },
    ...store('uncommon'),
  },
];

// -----------------------------------------------------------------------------
// Wearables
// -----------------------------------------------------------------------------

const headwear: CosmeticItemInput[] = [
  {
    id: 'headwear.arcade-cans',
    slot: 'headwear',
    name: 'Arcade Cans',
    description: 'Neon headphones looping the attract-mode tune.',
    mesh: 'headphones',
    tint: ['#1e1530', '#3bf0ff'],
    ...store('rare'),
  },
  {
    id: 'headwear.sunflower',
    slot: 'headwear',
    name: 'Sunflower',
    description: 'Always turns to face the spotlight.',
    mesh: 'flower',
    tint: ['#ffd23f', '#5a3b2e'],
    ...store('common'),
  },
  {
    id: 'headwear.coral-feelers',
    slot: 'headwear',
    name: 'Coral Feelers',
    description: 'Wobbly coral antennae from the reef.',
    mesh: 'antenna',
    tint: ['#ff7a7a', '#ffd6e8'],
    ...store('uncommon'),
  },
  {
    id: 'headwear.snow-beanie',
    slot: 'headwear',
    name: 'Snowdrift Beanie',
    description: 'Frosty knit with a snowball pom.',
    mesh: 'beanie-pom',
    tint: ['#a8e1ff', '#ffffff'],
    ...store('common'),
  },
  {
    id: 'headwear.orbit-ring',
    slot: 'headwear',
    name: 'Orbit Ring',
    description: 'A tiny planetary ring circling your head.',
    mesh: 'halo',
    tint: ['#7cf2ff'],
    ...store('epic'),
  },
  {
    id: 'headwear.captain',
    slot: 'headwear',
    name: 'Captain Topper',
    description: 'A navy top hat with a gold band. Aye aye.',
    mesh: 'top-hat',
    tint: ['#1b3a6b', '#ffd23f'],
    ...store('rare'),
  },
  {
    id: 'headwear.glowstick-cone',
    slot: 'headwear',
    name: 'Glowstick Cone',
    description: 'A party cone that glows in three flavours.',
    mesh: 'party-cone',
    tint: ['#3bf0ff', '#ff3bd4', '#b6ff3b'],
    ...store('uncommon'),
  },
  {
    id: 'headwear.snow-hare',
    slot: 'headwear',
    name: 'Snow Hare Ears',
    description: 'Long white ears with an icy lining.',
    mesh: 'bunny-ears',
    tint: ['#ffffff', '#a8e1ff'],
    ...store('rare'),
  },
  {
    id: 'headwear.little-devil',
    slot: 'headwear',
    name: 'Little Devil',
    description: 'Red horns for completely innocent grabbing.',
    mesh: 'horns',
    tint: ['#e53935', '#2a2238'],
    ...store('epic'),
  },
  {
    id: 'headwear.bonsai',
    slot: 'headwear',
    name: 'Bonsai Sprig',
    description: 'A carefully pruned sprout. Very zen.',
    mesh: 'sprout',
    tint: ['#2fbf71'],
    ...store('uncommon'),
  },
  {
    id: 'headwear.tabby-ears',
    slot: 'headwear',
    name: 'Tabby Ears',
    description: 'Ginger cat ears with cream insides.',
    mesh: 'cat-ears',
    tint: ['#ff8a3d', '#fff1c9'],
    ...store('uncommon'),
  },
  {
    id: 'headwear.pizza-chef',
    slot: 'headwear',
    name: 'Pizza Chef',
    description: 'A floury hat for throwing dough mid-race.',
    mesh: 'chef-hat',
    tint: ['#fff1e0'],
    ...store('common'),
  },
  {
    id: 'headwear.sky-pilot',
    slot: 'headwear',
    name: 'Sky Pilot Cap',
    description: 'Green propeller cap for aspiring aviators.',
    mesh: 'propeller-cap',
    tint: ['#2fbf71', '#ffffff', '#ff8a3d'],
    ...store('rare'),
  },
];

const back: CosmeticItemInput[] = [
  {
    id: 'back.turbo-boosters',
    slot: 'back',
    name: 'Turbo Boosters',
    description: 'Neon rockets with a joystick on top.',
    mesh: 'jetpack',
    tint: ['#2a2238', '#ff3bd4'],
    ...store('epic'),
  },
  {
    id: 'back.ladybug',
    slot: 'back',
    name: 'Ladybug Shell',
    description: 'Red with black spots. Brings good luck.',
    mesh: 'shell',
    tint: ['#e53935', '#2a2238'],
    ...store('rare'),
  },
  {
    id: 'back.mermaid-tail',
    slot: 'back',
    name: 'Mermaid Tail',
    description: 'A shimmering teal tail with violet fins.',
    mesh: 'tail',
    tint: ['#3fd0c9', '#9b5cff'],
    ...store('epic'),
  },
  {
    id: 'back.penguin-pack',
    slot: 'back',
    name: 'Penguin Pack',
    description: 'A tuxedo backpack. Fish sticks inside.',
    mesh: 'backpack',
    tint: ['#2a2238', '#ffffff'],
    ...store('uncommon'),
  },
  {
    id: 'back.monarch-wings',
    slot: 'back',
    name: 'Monarch Wings',
    description: 'Orange-and-ink butterfly wings.',
    mesh: 'wings',
    tint: ['#ff8a3d', '#2a2238'],
    ...store('legendary'),
  },
  {
    id: 'back.midnight-cape',
    slot: 'back',
    name: 'Midnight Cape',
    description: 'A starless cape with a violet lining.',
    mesh: 'cape',
    tint: ['#1e1530', '#7c5cff'],
    ...store('rare'),
  },
  {
    id: 'back.fox-tail',
    slot: 'back',
    name: 'Fox Tail',
    description: 'A bushy orange tail with a white tip.',
    mesh: 'tail',
    tint: ['#ff8a3d', '#ffffff'],
    ...store('uncommon'),
  },
  {
    id: 'back.aurora-wings',
    slot: 'back',
    name: 'Aurora Wings',
    description: 'Wings that shimmer like the northern lights.',
    mesh: 'wings',
    tint: ['#7cf2ff', '#ff4fd8'],
    ...store('mythic'),
  },
];

const upper: CosmeticItemInput[] = [
  {
    id: 'upper.petal-scarf',
    slot: 'upper',
    name: 'Petal Scarf',
    description: 'Pink petals stitched onto green knit.',
    mesh: 'scarf',
    tint: ['#ffb3d9', '#5fd16b'],
    ...store('uncommon'),
  },
  {
    id: 'upper.icicle-scarf',
    slot: 'upper',
    name: 'Icicle Scarf',
    description: 'Frosty stripes for the snowy islands.',
    mesh: 'scarf',
    tint: ['#a8e1ff', '#ffffff'],
    ...store('uncommon'),
  },
  {
    id: 'upper.neon-bow',
    slot: 'upper',
    name: 'Neon Bow Tie',
    description: 'A glowing cyan bow tie.',
    mesh: 'bow-tie',
    tint: ['#3bf0ff'],
    ...store('rare'),
  },
  {
    id: 'upper.gold-star',
    slot: 'upper',
    name: 'Gold Star Medal',
    description: 'For outstanding effort in tumbling.',
    mesh: 'medal',
    tint: ['#ffd23f', '#7c5cff'],
    ...store('epic'),
  },
  {
    id: 'upper.polka-bow',
    slot: 'upper',
    name: 'Polka Bow',
    description: 'A cheerful red bow tie.',
    mesh: 'bow-tie',
    tint: ['#e53935'],
    ...store('common'),
  },
  {
    id: 'upper.checkered-scarf',
    slot: 'upper',
    name: 'Checkered Scarf',
    description: 'Black and white, like the finish line.',
    mesh: 'scarf',
    tint: ['#2a2238', '#ffffff'],
    ...store('rare'),
  },
];

const lower: CosmeticItemInput[] = [
  {
    id: 'lower.daisy-tutu',
    slot: 'lower',
    name: 'Daisy Tutu',
    description: 'Buttery yellow tulle like a daisy centre.',
    mesh: 'tutu',
    tint: ['#fff3b0'],
    ...store('uncommon'),
  },
  {
    id: 'lower.life-ring',
    slot: 'lower',
    name: 'Life Ring',
    description: 'Red and white. Floats. Probably.',
    mesh: 'floatie',
    tint: ['#ff5a6e', '#ffffff'],
    ...store('rare'),
  },
  {
    id: 'lower.black-belt',
    slot: 'lower',
    name: 'Black Belt',
    description: 'Mastery of the ancient art of the dive.',
    mesh: 'belt',
    tint: ['#2a2238', '#ffffff'],
    ...store('rare'),
  },
  {
    id: 'lower.board-shorts',
    slot: 'lower',
    name: 'Board Shorts',
    description: 'Teal with yellow stripes. Surf is up.',
    mesh: 'shorts-stripes',
    tint: ['#3fd0c9', '#ffe14d'],
    ...store('common'),
  },
  {
    id: 'lower.glow-tutu',
    slot: 'lower',
    name: 'Glow Tutu',
    description: 'Lime tulle that glows under stage lights.',
    mesh: 'tutu',
    tint: ['#b6ff3b'],
    ...store('epic'),
  },
  {
    id: 'lower.rubber-ducky',
    slot: 'lower',
    name: 'Rubber Ducky',
    description: 'A floatie with a beak. Squeak.',
    mesh: 'floatie',
    tint: ['#ffd23f', '#ff8a3d'],
    ...store('epic'),
  },
];

// -----------------------------------------------------------------------------
// Emotes, celebrations, victory poses
// -----------------------------------------------------------------------------

const clips: CosmeticItemInput[] = [
  {
    id: 'emote.long-distance-hi',
    slot: 'emote',
    name: 'Long Distance Hi',
    description: 'A wave you can see from the next island.',
    clip: 'wave',
    ...store('common'),
  },
  {
    id: 'emote.snort-laugh',
    slot: 'emote',
    name: 'Snort Laugh',
    description: 'Laughing so hard it comes out of your nose.',
    clip: 'laugh',
    ...store('uncommon'),
  },
  {
    id: 'emote.gym-selfie',
    slot: 'emote',
    name: 'Gym Selfie',
    description: 'Flex for the camera. Every rep counts.',
    clip: 'flex',
    ...store('uncommon'),
  },
  {
    id: 'emote.washing-machine',
    slot: 'emote',
    name: 'Washing Machine',
    description: 'Spin cycle, but make it a dance move.',
    clip: 'spin',
    ...store('rare'),
  },
  {
    id: 'emote.grand-bow',
    slot: 'emote',
    name: 'Grand Bow',
    description: 'A deep and very serious bow.',
    clip: 'bow',
    ...store('rare'),
  },
  {
    id: 'emote.no-clue',
    slot: 'emote',
    name: 'No Clue',
    description: 'The finish was which way?',
    clip: 'shrug',
    ...store('common'),
  },
  {
    id: 'emote.disco-fever',
    slot: 'emote',
    name: 'Disco Fever',
    description: 'Strike a groove under the mirror ball.',
    clip: 'dance',
    ...store('epic'),
  },
  {
    id: 'emote.pom-pom',
    slot: 'emote',
    name: 'Pom-Pom Party',
    description: 'Gimme a T! Gimme a U!',
    clip: 'cheer',
    ...store('rare'),
  },
  {
    id: 'celebration.victory-lap',
    slot: 'celebration',
    name: 'Victory Lap',
    description: 'A little spin past the finish line.',
    clip: 'spin',
    ...store('uncommon'),
  },
  {
    id: 'celebration.star-jumps',
    slot: 'celebration',
    name: 'Star Jumps',
    description: 'Burn off the leftover adrenaline.',
    clip: 'jumping-jacks',
    ...store('uncommon'),
  },
  {
    id: 'celebration.main-event',
    slot: 'celebration',
    name: 'Main Event Flex',
    description: 'Champion muscles, on display.',
    clip: 'flex',
    ...store('rare'),
  },
  {
    id: 'celebration.crowd-pleaser',
    slot: 'celebration',
    name: 'Crowd Pleaser',
    description: 'Get the whole stadium on its feet.',
    clip: 'cheer',
    ...store('rare'),
  },
  {
    id: 'celebration.moonsault',
    slot: 'celebration',
    name: 'Moonsault',
    description: 'A backflip with a full moon of hang time.',
    clip: 'backflip',
    ...store('legendary'),
  },
  {
    id: 'victory.curtain-call',
    slot: 'victory',
    name: 'Curtain Call',
    description: 'One last bow as the confetti falls.',
    clip: 'bow',
    ...store('epic'),
  },
  {
    id: 'victory.stadium-roar',
    slot: 'victory',
    name: 'Stadium Roar',
    description: 'Arms up, crowd wild.',
    clip: 'cheer',
    ...store('epic'),
  },
  {
    id: 'victory.gold-flex',
    slot: 'victory',
    name: 'Gold Medal Flex',
    description: 'The pose of someone who never doubted it.',
    clip: 'flex',
    ...store('legendary'),
  },
  {
    id: 'victory.spotlight-spin',
    slot: 'victory',
    name: 'Spotlight Spin',
    description: 'A twirl under a single spotlight.',
    clip: 'victory-twirl',
    ...store('epic'),
  },
];

// -----------------------------------------------------------------------------
// Profile & VFX
// -----------------------------------------------------------------------------

const profile: CosmeticItemInput[] = [
  {
    id: 'nameplate.high-score',
    slot: 'nameplate',
    name: 'High Score',
    description: 'Your name at the top of the cabinet.',
    plate: { style: 'neon', bg: '#120d24', bg2: '#1e1638', text: '#3bf0ff', border: '#ff3bd4' },
    ...store('rare'),
  },
  {
    id: 'nameplate.rose-petal',
    slot: 'nameplate',
    name: 'Rose Petal',
    description: 'Soft pink with a leafy rim.',
    plate: { style: 'bubble', bg: '#ffb3d9', bg2: '#ffd6ec', text: '#7a2d55', border: '#5fd16b' },
    ...store('uncommon'),
  },
  {
    id: 'nameplate.sonar',
    slot: 'nameplate',
    name: 'Sonar Ping',
    description: 'Deep blue with a teal echo.',
    plate: { style: 'pill', bg: '#1b3a6b', bg2: '#2f5d9e', text: '#a8e1ff', border: '#3fd0c9' },
    ...store('uncommon'),
  },
  {
    id: 'nameplate.frosted',
    slot: 'nameplate',
    name: 'Frosted Glass',
    description: 'Cool and clear as an ice window.',
    plate: { style: 'bubble', bg: '#e6f6ff', bg2: '#ffffff', text: '#2b5d8a', border: '#a8e1ff' },
    ...store('common'),
  },
  {
    id: 'nameplate.mission',
    slot: 'nameplate',
    name: 'Mission Control',
    description: 'A launch ticket with a gold countdown.',
    plate: { style: 'ticket', bg: '#2a2238', bg2: '#3d3157', text: '#ffd23f', border: '#7cf2ff' },
    ...store('epic'),
  },
  {
    id: 'nameplate.champion',
    slot: 'nameplate',
    name: 'Champion Ribbon',
    description: 'A gold ribbon for the very best.',
    plate: { style: 'ribbon', bg: '#ffb000', bg2: '#ffd86b', text: '#4a2f22', border: '#ffffff' },
    ...store('legendary'),
  },
  {
    id: 'banner.game-over',
    slot: 'banner',
    name: 'Game Over',
    description: 'Insert coin to continue.',
    banner: { motif: 'stripes', colors: ['#1e1530', '#3bf0ff', '#ff3bd4'] },
    ...store('uncommon'),
  },
  {
    id: 'banner.flower-bed',
    slot: 'banner',
    name: 'Flower Bed',
    description: 'A riot of spring blooms.',
    banner: { motif: 'confetti', colors: ['#5fd16b', '#ffb3d9', '#ffd23f'] },
    ...store('common'),
  },
  {
    id: 'banner.coral-reef',
    slot: 'banner',
    name: 'Coral Reef',
    description: 'Gentle waves over a busy reef.',
    banner: { motif: 'waves', colors: ['#1b3a6b', '#3fd0c9', '#ff7a7a'] },
    ...store('rare'),
  },
  {
    id: 'banner.snowfall',
    slot: 'banner',
    name: 'Snowfall',
    description: 'Fat flakes over a quiet sky.',
    banner: { motif: 'clouds', colors: ['#a8e1ff', '#e6f6ff', '#ffffff'] },
    ...store('uncommon'),
  },
  {
    id: 'banner.orbit',
    slot: 'banner',
    name: 'Orbit',
    description: 'Planets, stars and a long way down.',
    banner: { motif: 'stars', colors: ['#0d0a1f', '#7cf2ff', '#ffd23f'] },
    ...store('epic'),
  },
  {
    id: 'banner.lava-flow',
    slot: 'banner',
    name: 'Lava Flow',
    description: 'Molten waves. Do not touch.',
    banner: { motif: 'waves', colors: ['#ff4f1f', '#ffb02e', '#2a2238'] },
    ...store('legendary'),
  },
];

const vfx: CosmeticItemInput[] = [
  {
    id: 'trail.pixel-sparks',
    slot: 'trail',
    name: 'Pixel Sparks',
    description: 'Glitchy neon sparks behind every step.',
    trail: { kind: 'sparkle', colors: ['#3bf0ff', '#ff3bd4'] },
    ...store('rare'),
  },
  {
    id: 'trail.petal-drift',
    slot: 'trail',
    name: 'Petal Drift',
    description: 'Pink petals float in your wake.',
    trail: { kind: 'hearts', colors: ['#ffb3d9', '#ffffff'] },
    ...store('uncommon'),
  },
  {
    id: 'trail.reef-bubbles',
    slot: 'trail',
    name: 'Reef Bubbles',
    description: 'Teal bubbles from the deep.',
    trail: { kind: 'bubbles', colors: ['#3fd0c9', '#a8e1ff'] },
    ...store('common'),
  },
  {
    id: 'trail.snow-flurry',
    slot: 'trail',
    name: 'Snow Flurry',
    description: 'A little blizzard follows you around.',
    trail: { kind: 'sparkle', colors: ['#ffffff', '#a8e1ff'] },
    ...store('uncommon'),
  },
  {
    id: 'trail.stardust',
    slot: 'trail',
    name: 'Stardust Wake',
    description: 'Cyan and gold stars streak behind you.',
    trail: { kind: 'stars', colors: ['#7cf2ff', '#ffd23f'] },
    ...store('epic'),
  },
  {
    id: 'trail.ember',
    slot: 'trail',
    name: 'Ember Streak',
    description: 'A blazing streak of molten colour.',
    trail: { kind: 'rainbow', colors: ['#ff4f1f', '#ff8a3d', '#ffd23f', '#fff3a0'] },
    ...store('legendary'),
  },
  {
    id: 'trail.birthday',
    slot: 'trail',
    name: 'Birthday Bash',
    description: 'Every round is your birthday.',
    trail: { kind: 'confetti', colors: ['#ff4f8b', '#3fa9ff', '#ffd23f', '#5fd16b'] },
    ...store('epic'),
  },
  {
    id: 'footsteps.frosty',
    slot: 'footsteps',
    name: 'Frosty Squeaks',
    description: 'The squeak of fresh snow.',
    pack: 'squeak',
    ...store('uncommon'),
  },
  {
    id: 'footsteps.bubble-boots',
    slot: 'footsteps',
    name: 'Bubble Boots',
    description: 'Squishy soles that leave you bouncing.',
    pack: 'jelly',
    ...store('rare'),
  },
  {
    id: 'footsteps.drum-roll',
    slot: 'footsteps',
    name: 'Drum Roll',
    description: 'Every step builds the suspense.',
    pack: 'tap',
    ...store('rare'),
  },
  {
    id: 'footsteps.wind-chimes',
    slot: 'footsteps',
    name: 'Wind Chimes',
    description: 'A soft tinkle with every stride.',
    pack: 'bell',
    ...store('epic'),
  },
  {
    id: 'footsteps.trampoline',
    slot: 'footsteps',
    name: 'Trampoline Toes',
    description: 'Boing. Boing. Boing.',
    pack: 'boing',
    ...store('rare'),
  },
];

/** Every item-shop cosmetic, in catalog order (order feeds the seeded rotations). */
export const STORE_COLLECTION: readonly CosmeticItemInput[] = [
  ...skins,
  ...patterns,
  ...faces,
  ...headwear,
  ...back,
  ...upper,
  ...lower,
  ...clips,
  ...profile,
  ...vfx,
];

// -----------------------------------------------------------------------------
// Themed sets (sold as bundles)
// -----------------------------------------------------------------------------

/** A themed set of store items the shop sells together at a discount. */
export interface StoreSet {
  /** Stable id `bundle.<kebab-name>`; the offer id is `bundle:<id>`. */
  id: string;
  name: string;
  description: string;
  /** Store item ids; the first is the hero shown on the bundle card. All share one currency. */
  itemIds: readonly string[];
}

/** Every bundle the store sells. Validated by the content tests. */
export const STORE_SETS: readonly StoreSet[] = [
  {
    id: 'bundle.arcade-night',
    name: 'Arcade Night',
    description: 'Neon colours, glowing cans and a rocket pack for the high-score chase.',
    itemIds: [
      'back.turbo-boosters',
      'color.arcade-neon',
      'headwear.arcade-cans',
      'face.arcade-shades',
      'trail.pixel-sparks',
      'nameplate.high-score',
    ],
  },
  {
    id: 'bundle.garden-party',
    name: 'Garden Party',
    description: 'Petals, ladybugs and a sunflower for the springtime islands.',
    itemIds: [
      'back.ladybug',
      'color.rose-garden',
      'headwear.sunflower',
      'upper.petal-scarf',
      'lower.daisy-tutu',
      'trail.petal-drift',
    ],
  },
  {
    id: 'bundle.deep-sea',
    name: 'Deep Sea',
    description: 'A mermaid tail, coral feelers and bubbles from the deep.',
    itemIds: [
      'back.mermaid-tail',
      'color.abyss',
      'pattern.tide',
      'headwear.coral-feelers',
      'lower.life-ring',
      'trail.reef-bubbles',
    ],
  },
  {
    id: 'bundle.snow-day',
    name: 'Snow Day',
    description: 'Bundle up: beanie, scarf, penguin pack and a flurry of snow.',
    itemIds: [
      'headwear.snow-beanie',
      'color.frostbite',
      'upper.icicle-scarf',
      'back.penguin-pack',
      'trail.snow-flurry',
      'footsteps.frosty',
    ],
  },
  {
    id: 'bundle.space-cadet',
    name: 'Space Cadet',
    description: 'Moon dust, an orbit ring and a visor for zero-gravity rounds.',
    itemIds: [
      'headwear.orbit-ring',
      'color.moon-dust',
      'pattern.starfield',
      'face.astro-visor',
      'nameplate.mission',
      'banner.orbit',
      'trail.stardust',
    ],
  },
];
