/**
 * Launch cosmetics catalog. Every name and design here is original.
 *
 * Responsibilities:
 * - Declares every launch item, validated once at module load.
 * - Provides id lookup and per-slot listings.
 *
 * Prices follow one curve per rarity so the store stays coherent; premium
 * (Gems) pricing is reserved for Legendary/Mythic store items.
 */
import {
  CosmeticItemSchema,
  type CosmeticItem,
  type CosmeticItemInput,
  type CosmeticSlot,
  type Currency,
  type Rarity,
} from './schema.ts';

type Price = { currency: Currency; amount: number } | null;

/** Store price per rarity. */
const STORE_PRICE: Readonly<Record<Rarity, Price>> = {
  common: { currency: 'gumballs', amount: 400 },
  uncommon: { currency: 'gumballs', amount: 800 },
  rare: { currency: 'gumballs', amount: 1500 },
  epic: { currency: 'gumballs', amount: 3000 },
  legendary: { currency: 'gems', amount: 800 },
  mythic: { currency: 'gems', amount: 1600 },
};

type Src = 'default' | 'store' | 'pass' | 'challenge' | 'event';
const meta = (rarity: Rarity, source: Src): { rarity: Rarity; source: Src; price: Price } => ({
  rarity,
  source,
  price: source === 'store' ? STORE_PRICE[rarity] : null,
});

// -----------------------------------------------------------------------------
// Colours
// -----------------------------------------------------------------------------

const colors: CosmeticItemInput[] = [
  {
    id: 'color.bubblegum',
    slot: 'color',
    name: 'Bubblegum',
    description: 'The classic. Chewy, pink and ready to tumble.',
    colors: ['#ff6fb5', '#ffd23f', '#7c5cff'],
    ...meta('common', 'default'),
  },
  {
    id: 'color.mint-chip',
    slot: 'color',
    name: 'Mint Chip',
    description: 'Cool mint with chocolate chunks.',
    colors: ['#7ff0c8', '#5a3b2e', '#fff7ec'],
    ...meta('common', 'default'),
  },
  {
    id: 'color.lemon-drop',
    slot: 'color',
    name: 'Lemon Drop',
    description: 'Sour, sunny, a little bit zesty.',
    colors: ['#ffe14d', '#ff8a3d', '#ffffff'],
    ...meta('common', 'default'),
  },
  {
    id: 'color.blueberry',
    slot: 'color',
    name: 'Blueberry Burst',
    description: 'Fresh from the bush, extra juicy.',
    colors: ['#4d8dff', '#a8e1ff', '#2b1d6a'],
    ...meta('common', 'store'),
  },
  {
    id: 'color.grape-fizz',
    slot: 'color',
    name: 'Grape Fizz',
    description: 'Bubbly purple with a sparkling finish.',
    colors: ['#9b5cff', '#ff9ef0', '#40e0d0'],
    ...meta('uncommon', 'store'),
  },
  {
    id: 'color.tangerine',
    slot: 'color',
    name: 'Tangerine Twist',
    description: 'Peel-fresh orange with a cream swirl.',
    colors: ['#ff8a3d', '#fff1c9', '#ff4f8b'],
    ...meta('uncommon', 'challenge'),
  },
  {
    id: 'color.cotton-cloud',
    slot: 'color',
    name: 'Cotton Cloud',
    description: 'Spun-sugar pastels, light as air.',
    colors: ['#ffc4e8', '#b8e7ff', '#fff3b0'],
    ...meta('rare', 'store'),
  },
  {
    id: 'color.licorice',
    slot: 'color',
    name: 'Licorice Night',
    description: 'Dark, glossy and a little mysterious.',
    colors: ['#2a2238', '#ff4f8b', '#7cf2ff'],
    ...meta('rare', 'pass'),
  },
  {
    id: 'color.sea-salt',
    slot: 'color',
    name: 'Sea Salt Taffy',
    description: 'Beach-boardwalk teal with a sandy trim.',
    colors: ['#3fd0c9', '#ffe5b4', '#ff7a7a'],
    ...meta('uncommon', 'store'),
  },
  {
    id: 'color.watermelon',
    slot: 'color',
    name: 'Watermelon Slice',
    description: 'Summer in squishy form. Seeds not included.',
    colors: ['#ff5a6e', '#5fd16b', '#2b2b2b'],
    ...meta('rare', 'store'),
  },
  {
    id: 'color.toasted',
    slot: 'color',
    name: 'Toasted Mallow',
    description: 'Golden on the outside, gooey inside.',
    colors: ['#f2b880', '#fff8ee', '#8a5a3c'],
    ...meta('epic', 'challenge'),
  },
  {
    id: 'color.neon-lime',
    slot: 'color',
    name: 'Neon Lime',
    description: 'Visible from three islands away.',
    colors: ['#b6ff3b', '#1e1e2e', '#ff3bd4'],
    ...meta('epic', 'store'),
  },
  {
    id: 'color.sherbet',
    slot: 'color',
    name: 'Rainbow Sherbet',
    description: 'All the flavours, none of the brain freeze.',
    colors: ['#ff8fb1', '#ffd36e', '#7fe3ff'],
    ...meta('legendary', 'store'),
  },
];

// -----------------------------------------------------------------------------
// Patterns
// -----------------------------------------------------------------------------

const patterns: CosmeticItemInput[] = [
  {
    id: 'pattern.solid',
    slot: 'pattern',
    name: 'Plain & Proud',
    description: 'No frills. Maximum squish.',
    pattern: 'solid',
    ...meta('common', 'default'),
  },
  {
    id: 'pattern.stripes',
    slot: 'pattern',
    name: 'Candy Stripes',
    description: 'Peppermint-pole stripes, tilted for speed.',
    pattern: 'stripes',
    angle: 20,
    ...meta('common', 'default'),
  },
  {
    id: 'pattern.dots',
    slot: 'pattern',
    name: 'Polka Party',
    description: 'Dots on dots on dots.',
    pattern: 'dots',
    ...meta('common', 'default'),
  },
  {
    id: 'pattern.camo',
    slot: 'pattern',
    name: 'Gumdrop Camo',
    description: 'Blend into any candy shop.',
    pattern: 'camo',
    ...meta('uncommon', 'store'),
  },
  {
    id: 'pattern.gradient',
    slot: 'pattern',
    name: 'Sunset Fade',
    description: 'A smooth melt from head to toe.',
    pattern: 'gradient',
    ...meta('uncommon', 'store'),
  },
  {
    id: 'pattern.galaxy',
    slot: 'pattern',
    name: 'Cosmic Swirl',
    description: 'Stars, nebulae and a hint of stardust.',
    pattern: 'galaxy',
    ...meta('legendary', 'store'),
  },
  {
    id: 'pattern.checker',
    slot: 'pattern',
    name: 'Finish Flag',
    description: 'Always looks like you just won.',
    pattern: 'checker',
    ...meta('rare', 'pass'),
  },
  {
    id: 'pattern.zigzag',
    slot: 'pattern',
    name: 'Zig Zag Zoom',
    description: 'Lightning-fast zigzags.',
    pattern: 'zigzag',
    ...meta('uncommon', 'store'),
  },
  {
    id: 'pattern.hearts',
    slot: 'pattern',
    name: 'Sweetheart',
    description: 'Covered head to toe in love.',
    pattern: 'hearts',
    ...meta('rare', 'store'),
  },
  {
    id: 'pattern.spots',
    slot: 'pattern',
    name: 'Cookie Spots',
    description: 'Chocolate-chip blotches, freshly baked.',
    pattern: 'spots',
    ...meta('uncommon', 'challenge'),
  },
  {
    id: 'pattern.swirl',
    slot: 'pattern',
    name: 'Lollipop Swirl',
    description: 'Hypnotic spirals. Do not stare.',
    pattern: 'swirl',
    ...meta('epic', 'store'),
  },
  {
    id: 'pattern.split',
    slot: 'pattern',
    name: 'Two Tone',
    description: 'Half one thing, half another.',
    pattern: 'split',
    ...meta('rare', 'store'),
  },
  {
    id: 'pattern.sprinkles',
    slot: 'pattern',
    name: 'Sprinkle Shower',
    description: 'Freshly dunked in rainbow sprinkles.',
    pattern: 'sprinkles',
    ...meta('epic', 'pass'),
  },
  {
    id: 'pattern.plaid',
    slot: 'pattern',
    name: 'Picnic Plaid',
    description: 'Cosy enough for a lakeside lunch.',
    pattern: 'plaid',
    ...meta('rare', 'store'),
  },
  {
    id: 'pattern.waves',
    slot: 'pattern',
    name: 'Ripple Pop',
    description: 'Wobbly bands like a fizzy drink.',
    pattern: 'waves',
    ...meta('uncommon', 'store'),
  },
  {
    id: 'pattern.diamonds',
    slot: 'pattern',
    name: 'Harlequin',
    description: 'Jester diamonds for the show-off.',
    pattern: 'diamonds',
    ...meta('epic', 'challenge'),
  },
];

// -----------------------------------------------------------------------------
// Faces
// -----------------------------------------------------------------------------

const faces: CosmeticItemInput[] = [
  {
    id: 'face.classic',
    slot: 'face',
    name: 'Bright Eyes',
    description: 'Wide-eyed and always up for it.',
    face: {},
    ...meta('common', 'default'),
  },
  {
    id: 'face.sleepy',
    slot: 'face',
    name: 'Five More Minutes',
    description: 'Permanently half-awake.',
    face: { lidRest: 0.4, iris: '#5a7bd8' },
    ...meta('common', 'store'),
  },
  {
    id: 'face.starry',
    slot: 'face',
    name: 'Starstruck',
    description: 'Sees stars even when not stunned.',
    face: { pupil: 'star', iris: '#ffb02e', eyeScale: 1.08 },
    ...meta('rare', 'store'),
  },
  {
    id: 'face.lovestruck',
    slot: 'face',
    name: 'Lovestruck',
    description: 'Heart-shaped pupils, heart-shaped dreams.',
    face: { pupil: 'heart', iris: '#ff4f8b', lashes: true },
    ...meta('rare', 'pass'),
  },
  {
    id: 'face.kitty',
    slot: 'face',
    name: 'Kitty Gaze',
    description: 'Slit pupils. Judging you, politely.',
    face: { pupil: 'cat', iris: '#6ee06e' },
    ...meta('uncommon', 'store'),
  },
  {
    id: 'face.freckles',
    slot: 'face',
    name: 'Sun Kissed',
    description: 'Freckles from a summer on the beach islands.',
    face: { freckles: true, iris: '#8a5a3c' },
    ...meta('uncommon', 'challenge'),
  },
  {
    id: 'face.hypno',
    slot: 'face',
    name: 'Dizzy Dazzle',
    description: 'Spiral eyes. Still somehow runs straight.',
    face: { pupil: 'spiral', iris: '#7c5cff', eyeScale: 1.1 },
    ...meta('epic', 'store'),
  },
  {
    id: 'face.visor',
    slot: 'face',
    name: 'Speed Visor',
    description: 'Aerodynamic shades for serious racers.',
    face: { accessory: 'visor', tint: ['#2bd0ff'] },
    ...meta('epic', 'store'),
  },
  {
    id: 'face.specs',
    slot: 'face',
    name: 'Smarty Specs',
    description: 'Round glasses. Reads the course in advance.',
    face: { accessory: 'glasses', tint: ['#2a2238'] },
    ...meta('uncommon', 'store'),
  },
  {
    id: 'face.mustache',
    slot: 'face',
    name: 'Dapper Lip',
    description: 'A magnificent curly mustache.',
    face: { accessory: 'mustache', tint: ['#4a2f22'] },
    ...meta('rare', 'store'),
  },
  {
    id: 'face.monocle',
    slot: 'face',
    name: 'Fancy Monocle',
    description: 'Distinguished. Possibly a tumbling aristocrat.',
    face: { accessory: 'monocle', tint: ['#ffcf4a'], lashes: true },
    ...meta('epic', 'pass'),
  },
  {
    id: 'face.star-shades',
    slot: 'face',
    name: 'Superstar Shades',
    description: 'Star-shaped sunglasses for main characters.',
    face: { accessory: 'star-shades', tint: ['#ff3bd4'] },
    ...meta('legendary', 'store'),
  },
];

// -----------------------------------------------------------------------------
// Wearables
// -----------------------------------------------------------------------------

const headwear: CosmeticItemInput[] = [
  {
    id: 'headwear.party-cone',
    slot: 'headwear',
    name: 'Party Starter',
    description: 'A striped cone hat with a fluffy tip.',
    mesh: 'party-cone',
    tint: ['#ff4f8b', '#ffd23f', '#ffffff'],
    ...meta('common', 'default'),
  },
  {
    id: 'headwear.beanie',
    slot: 'headwear',
    name: 'Bobble Beanie',
    description: 'Knitted warmth with a bouncy pom.',
    mesh: 'beanie-pom',
    tint: ['secondary', '#ffffff'],
    ...meta('common', 'store'),
  },
  {
    id: 'headwear.tiara',
    slot: 'headwear',
    name: 'Sugar Tiara',
    description: 'Glittering, sparkling, totally regal.',
    mesh: 'tiara',
    tint: ['#ffd23f', '#7cf2ff'],
    ...meta('epic', 'store'),
  },
  {
    id: 'headwear.chef',
    slot: 'headwear',
    name: 'Head Baker',
    description: 'For Tumblers who are cooking.',
    mesh: 'chef-hat',
    tint: ['#ffffff'],
    ...meta('uncommon', 'challenge'),
  },
  {
    id: 'headwear.horns',
    slot: 'headwear',
    name: 'Brave Horns',
    description: 'Chunky horns on a sturdy cap.',
    mesh: 'horns',
    tint: ['#b0b6c8', '#fff1c9'],
    ...meta('rare', 'store'),
  },
  {
    id: 'headwear.propeller',
    slot: 'headwear',
    name: 'Whirly Cap',
    description: 'Spins when you move. Does not fly. Yet.',
    mesh: 'propeller-cap',
    tint: ['#3fa9ff', '#ffd23f', '#ff4f8b'],
    ...meta('uncommon', 'store'),
  },
  {
    id: 'headwear.bunny',
    slot: 'headwear',
    name: 'Floppy Bunny',
    description: 'Ears that flop with every hop.',
    mesh: 'bunny-ears',
    tint: ['#ffffff', '#ffb3d9'],
    ...meta('rare', 'pass'),
  },
  {
    id: 'headwear.halo',
    slot: 'headwear',
    name: 'Angel Ring',
    description: 'A glowing halo. Totally innocent, honest.',
    mesh: 'halo',
    tint: ['#fff3a0'],
    ...meta('legendary', 'store'),
  },
  {
    id: 'headwear.top-hat',
    slot: 'headwear',
    name: 'Showtime Topper',
    description: 'A tall hat for the grand finale.',
    mesh: 'top-hat',
    tint: ['#2a2238', '#ff4f8b'],
    ...meta('epic', 'store'),
  },
  {
    id: 'headwear.flower',
    slot: 'headwear',
    name: 'Daisy Pop',
    description: 'A cheerful bloom tucked on top.',
    mesh: 'flower',
    tint: ['#ffffff', '#ffd23f'],
    ...meta('common', 'challenge'),
  },
  {
    id: 'headwear.antenna',
    slot: 'headwear',
    name: 'Boing Antennae',
    description: 'Wobbly feelers with glowing tips.',
    mesh: 'antenna',
    tint: ['#2a2238', '#b6ff3b'],
    ...meta('rare', 'store'),
  },
  {
    id: 'headwear.headphones',
    slot: 'headwear',
    name: 'Bass Bumpers',
    description: 'Chunky cans for the round-one playlist.',
    mesh: 'headphones',
    tint: ['#2a2238', 'primary'],
    ...meta('uncommon', 'store'),
  },
  {
    id: 'headwear.sprout',
    slot: 'headwear',
    name: 'Lil Sprout',
    description: 'A tiny leaf growing on top. Water daily.',
    mesh: 'sprout',
    tint: ['#5fd16b'],
    ...meta('common', 'store'),
  },
  {
    id: 'headwear.cat-ears',
    slot: 'headwear',
    name: 'Kitty Ears',
    description: 'Pointy and perky.',
    mesh: 'cat-ears',
    tint: ['primary', '#ffb3d9'],
    ...meta('uncommon', 'pass'),
  },
  {
    id: 'headwear.royal-tiara',
    slot: 'headwear',
    name: 'Gumdrop Majesty',
    description: 'Encrusted with sugar gems. Mythically shiny.',
    mesh: 'tiara',
    tint: ['#ff4fd8', '#7cf2ff'],
    ...meta('mythic', 'event'),
  },
];

const back: CosmeticItemInput[] = [
  {
    id: 'back.cape',
    slot: 'back',
    name: 'Hero Cape',
    description: 'Flaps dramatically in every breeze.',
    mesh: 'cape',
    tint: ['#ff4f8b', '#ffd23f'],
    ...meta('rare', 'store'),
  },
  {
    id: 'back.wings',
    slot: 'back',
    name: 'Sugar Wings',
    description: 'Translucent wings that flutter.',
    mesh: 'wings',
    tint: ['#bdf3ff', '#ffffff'],
    ...meta('epic', 'store'),
  },
  {
    id: 'back.jetpack',
    slot: 'back',
    name: 'Rocket Pack',
    description: 'Retro rockets. Decorative. Probably.',
    mesh: 'jetpack',
    tint: ['#c7cede', '#ff8a3d'],
    ...meta('legendary', 'store'),
  },
  {
    id: 'back.tail',
    slot: 'back',
    name: 'Wiggle Tail',
    description: 'Wags whenever you are happy.',
    mesh: 'tail',
    tint: ['primary', '#ffffff'],
    ...meta('uncommon', 'pass'),
  },
  {
    id: 'back.backpack',
    slot: 'back',
    name: 'Snack Pack',
    description: 'Holds at least eleven snacks.',
    mesh: 'backpack',
    tint: ['#3fa9ff', '#ffd23f'],
    ...meta('common', 'store'),
  },
  {
    id: 'back.shell',
    slot: 'back',
    name: 'Turtle Shell',
    description: 'Slow and steady? Not today.',
    mesh: 'shell',
    tint: ['#5fd16b', '#ffe5b4'],
    ...meta('rare', 'challenge'),
  },
  {
    id: 'back.royal-cape',
    slot: 'back',
    name: 'Velvet Mantle',
    description: 'Fit for whoever holds the Crown.',
    mesh: 'cape',
    tint: ['#7c2bd9', '#ffd23f'],
    ...meta('mythic', 'event'),
  },
];

const upper: CosmeticItemInput[] = [
  {
    id: 'upper.bow-tie',
    slot: 'upper',
    name: 'Bow Tie',
    description: 'Formal tumbling attire.',
    mesh: 'bow-tie',
    tint: ['#ff4f8b'],
    ...meta('common', 'store'),
  },
  {
    id: 'upper.scarf',
    slot: 'upper',
    name: 'Cosy Scarf',
    description: 'Trails behind you as you run.',
    mesh: 'scarf',
    tint: ['#ff5a6e', '#ffffff'],
    ...meta('uncommon', 'store'),
  },
  {
    id: 'upper.medal',
    slot: 'upper',
    name: 'Participation Medal',
    description: 'You showed up. That counts!',
    mesh: 'medal',
    tint: ['#ffcf4a', '#3fa9ff'],
    ...meta('common', 'challenge'),
  },
];

const lower: CosmeticItemInput[] = [
  {
    id: 'lower.belt',
    slot: 'lower',
    name: 'Champion Belt',
    description: 'A shiny buckle the size of a waffle.',
    mesh: 'belt',
    tint: ['#5a3b2e', '#ffcf4a'],
    ...meta('uncommon', 'store'),
  },
  {
    id: 'lower.tutu',
    slot: 'lower',
    name: 'Twirl Tutu',
    description: 'Ruffled tulle for maximum spin.',
    mesh: 'tutu',
    tint: ['#ffb3d9'],
    ...meta('rare', 'store'),
  },
  {
    id: 'lower.shorts',
    slot: 'lower',
    name: 'Sporty Shorts',
    description: 'Two racing stripes. Twice the speed.',
    mesh: 'shorts-stripes',
    tint: ['#3fa9ff', '#ffffff'],
    ...meta('common', 'default'),
  },
  {
    id: 'lower.floatie',
    slot: 'lower',
    name: 'Pool Floatie',
    description: 'Ready for any slime situation.',
    mesh: 'floatie',
    tint: ['#ffd23f', '#ff4f8b'],
    ...meta('epic', 'pass'),
  },
];

// -----------------------------------------------------------------------------
// Animations
// -----------------------------------------------------------------------------

const emotes: CosmeticItemInput[] = [
  {
    id: 'emote.wave',
    slot: 'emote',
    name: 'Hiya!',
    description: 'A big friendly wave.',
    clip: 'wave',
    ...meta('common', 'default'),
  },
  {
    id: 'emote.dance',
    slot: 'emote',
    name: 'Wiggle Jam',
    description: 'A bouncy little dance.',
    clip: 'dance',
    ...meta('common', 'default'),
  },
  {
    id: 'emote.laugh',
    slot: 'emote',
    name: 'Belly Laugh',
    description: 'Ha! Ha! Ha!',
    clip: 'laugh',
    ...meta('common', 'default'),
  },
  {
    id: 'emote.flex',
    slot: 'emote',
    name: 'Noodle Flex',
    description: 'Show off those mighty stubby arms.',
    clip: 'flex',
    ...meta('common', 'default'),
  },
  {
    id: 'emote.facepalm',
    slot: 'emote',
    name: 'Oh No',
    description: 'When the door was fake. Again.',
    clip: 'facepalm',
    ...meta('uncommon', 'store'),
  },
  {
    id: 'emote.spin',
    slot: 'emote',
    name: 'Top Spin',
    description: 'Spin like a toy top.',
    clip: 'spin',
    ...meta('rare', 'store'),
  },
  {
    id: 'emote.jumping-jacks',
    slot: 'emote',
    name: 'Warm Up',
    description: 'Jumping jacks before the big race.',
    clip: 'jumping-jacks',
    ...meta('uncommon', 'challenge'),
  },
  {
    id: 'emote.bow',
    slot: 'emote',
    name: 'Take a Bow',
    description: 'Thank you, thank you.',
    clip: 'bow',
    ...meta('rare', 'pass'),
  },
  {
    id: 'emote.shrug',
    slot: 'emote',
    name: 'Whatever',
    description: 'Who, me? No idea.',
    clip: 'shrug',
    ...meta('uncommon', 'store'),
  },
];

const celebrations: CosmeticItemInput[] = [
  {
    id: 'celebration.cheer',
    slot: 'celebration',
    name: 'Woo-Hoo!',
    description: 'Jump and cheer at the finish.',
    clip: 'cheer',
    ...meta('common', 'default'),
  },
  {
    id: 'celebration.fist-pump',
    slot: 'celebration',
    name: 'Yes! Yes!',
    description: 'Triple fist pump of triumph.',
    clip: 'fist-pump',
    ...meta('rare', 'store'),
  },
  {
    id: 'celebration.backflip',
    slot: 'celebration',
    name: 'Show-Off Flip',
    description: 'A backflip nobody asked for.',
    clip: 'backflip',
    ...meta('epic', 'store'),
  },
];

const victories: CosmeticItemInput[] = [
  {
    id: 'victory.superstar',
    slot: 'victory',
    name: 'Superstar',
    description: 'Arms high, soaking in the applause.',
    clip: 'victory-superstar',
    ...meta('common', 'default'),
  },
  {
    id: 'victory.hero',
    slot: 'victory',
    name: 'Hero Stance',
    description: 'Hands on hips, gazing into the distance.',
    clip: 'victory-hero',
    ...meta('rare', 'pass'),
  },
  {
    id: 'victory.twirl',
    slot: 'victory',
    name: 'Grand Twirl',
    description: 'A pirouette and a curtsey.',
    clip: 'victory-twirl',
    ...meta('legendary', 'store'),
  },
];

// -----------------------------------------------------------------------------
// Profile & VFX
// -----------------------------------------------------------------------------

const nameplates: CosmeticItemInput[] = [
  {
    id: 'nameplate.classic',
    slot: 'nameplate',
    name: 'Classic Pill',
    description: 'Clean and readable.',
    plate: { style: 'pill', bg: '#2a2238', bg2: '#3d3157', text: '#ffffff', border: '#ffffff' },
    ...meta('common', 'default'),
  },
  {
    id: 'nameplate.bubblegum',
    slot: 'nameplate',
    name: 'Bubble Pop',
    description: 'A bubbly pink plate.',
    plate: { style: 'bubble', bg: '#ff6fb5', bg2: '#ff9fd0', text: '#ffffff', border: '#ffe0f0' },
    ...meta('uncommon', 'store'),
  },
  {
    id: 'nameplate.ribbon',
    slot: 'nameplate',
    name: 'Prize Ribbon',
    description: 'First-place ribbon energy.',
    plate: { style: 'ribbon', bg: '#3fa9ff', bg2: '#77c4ff', text: '#ffffff', border: '#ffd23f' },
    ...meta('rare', 'pass'),
  },
  {
    id: 'nameplate.ticket',
    slot: 'nameplate',
    name: 'Admit One',
    description: 'A golden ticket to the show.',
    plate: { style: 'ticket', bg: '#ffd23f', bg2: '#ffe680', text: '#4a2f22', border: '#ff8a3d' },
    ...meta('epic', 'store'),
  },
  {
    id: 'nameplate.neon',
    slot: 'nameplate',
    name: 'Night Sign',
    description: 'Buzzing neon outline.',
    plate: { style: 'neon', bg: '#1e1530', bg2: '#2a1e45', text: '#7cf2ff', border: '#ff3bd4' },
    ...meta('legendary', 'store'),
  },
  {
    id: 'nameplate.mint',
    slot: 'nameplate',
    name: 'Fresh Mint',
    description: 'Cool and calm.',
    plate: { style: 'pill', bg: '#3fd0a8', bg2: '#7ff0c8', text: '#ffffff', border: '#e0fff4' },
    ...meta('common', 'challenge'),
  },
];

const banners: CosmeticItemInput[] = [
  {
    id: 'banner.confetti',
    slot: 'banner',
    name: 'Confetti Burst',
    description: 'Every day is a party.',
    banner: { motif: 'confetti', colors: ['#ff6fb5', '#ffd23f', '#5ce1e6'] },
    ...meta('common', 'default'),
  },
  {
    id: 'banner.clouds',
    slot: 'banner',
    name: 'Sky High',
    description: 'Fluffy clouds on a candy sky.',
    banner: { motif: 'clouds', colors: ['#5aa9ff', '#ffd6f2', '#ffffff'] },
    ...meta('common', 'store'),
  },
  {
    id: 'banner.stripes',
    slot: 'banner',
    name: 'Speedway',
    description: 'Racing stripes for racers.',
    banner: { motif: 'stripes', colors: ['#ff4f8b', '#ffffff', '#2a2238'] },
    ...meta('uncommon', 'challenge'),
  },
  {
    id: 'banner.stars',
    slot: 'banner',
    name: 'Starfield',
    description: 'A night sky full of wishes.',
    banner: { motif: 'stars', colors: ['#1e1530', '#7c5cff', '#ffd23f'] },
    ...meta('rare', 'store'),
  },
  {
    id: 'banner.candy',
    slot: 'banner',
    name: 'Sweet Shop',
    description: 'Lollipops and gumdrops galore.',
    banner: { motif: 'candy', colors: ['#ffc4e8', '#7ff0c8', '#ff8a3d'] },
    ...meta('epic', 'pass'),
  },
  {
    id: 'banner.waves',
    slot: 'banner',
    name: 'Goo Tide',
    description: 'Rolling waves of sparkly goo.',
    banner: { motif: 'waves', colors: ['#3fd0c9', '#9b5cff', '#ffffff'] },
    ...meta('legendary', 'store'),
  },
];

const trails: CosmeticItemInput[] = [
  {
    id: 'trail.sparkle',
    slot: 'trail',
    name: 'Glitter Dust',
    description: 'Leaves a sparkly path.',
    trail: { kind: 'sparkle', colors: ['#ffffff', '#ffd23f'] },
    ...meta('uncommon', 'store'),
  },
  {
    id: 'trail.bubbles',
    slot: 'trail',
    name: 'Bubble Wake',
    description: 'Pop, pop, pop.',
    trail: { kind: 'bubbles', colors: ['#bdf3ff', '#ffffff'] },
    ...meta('common', 'challenge'),
  },
  {
    id: 'trail.hearts',
    slot: 'trail',
    name: 'Love Trail',
    description: 'Hearts float up behind you.',
    trail: { kind: 'hearts', colors: ['#ff4f8b', '#ffb3d9'] },
    ...meta('rare', 'pass'),
  },
  {
    id: 'trail.confetti',
    slot: 'trail',
    name: 'Parade Route',
    description: 'A one-Tumbler parade.',
    trail: { kind: 'confetti', colors: ['#ff6fb5', '#ffd23f', '#5ce1e6', '#7c5cff'] },
    ...meta('epic', 'store'),
  },
  {
    id: 'trail.rainbow',
    slot: 'trail',
    name: 'Rainbow Dash',
    description: 'A full spectrum streak.',
    trail: { kind: 'rainbow', colors: ['#ff5a6e', '#ffd23f', '#5fd16b', '#3fa9ff'] },
    ...meta('legendary', 'store'),
  },
  {
    id: 'trail.stars',
    slot: 'trail',
    name: 'Comet Tail',
    description: 'Shooting stars at your heels.',
    trail: { kind: 'stars', colors: ['#fff3a0', '#ff8a3d'] },
    ...meta('mythic', 'event'),
  },
];

const footsteps: CosmeticItemInput[] = [
  {
    id: 'footsteps.squeak',
    slot: 'footsteps',
    name: 'Squeaky Toy',
    description: 'Every step squeaks.',
    pack: 'squeak',
    ...meta('common', 'default'),
  },
  {
    id: 'footsteps.boing',
    slot: 'footsteps',
    name: 'Spring Step',
    description: 'Boing, boing, boing.',
    pack: 'boing',
    ...meta('uncommon', 'store'),
  },
  {
    id: 'footsteps.tap',
    slot: 'footsteps',
    name: 'Tap Shoes',
    description: 'Clickety-clack on every surface.',
    pack: 'tap',
    ...meta('rare', 'store'),
  },
  {
    id: 'footsteps.jelly',
    slot: 'footsteps',
    name: 'Jelly Feet',
    description: 'Squelchy and proud of it.',
    pack: 'jelly',
    ...meta('uncommon', 'challenge'),
  },
  {
    id: 'footsteps.bell',
    slot: 'footsteps',
    name: 'Jingle Toes',
    description: 'Tiny bells. Hard to sneak.',
    pack: 'bell',
    ...meta('epic', 'pass'),
  },
];

// -----------------------------------------------------------------------------
// Season 1: Sugar Rush pass
// -----------------------------------------------------------------------------

const pass = (rarity: Rarity): { rarity: Rarity; source: Src; price: Price } => meta(rarity, 'pass');

const sugarRushColors: CosmeticItemInput[] = [
  {
    id: 'color.cherry-cola',
    slot: 'color',
    name: 'Cherry Cola',
    description: 'Fizzy red with a syrupy dark trim.',
    colors: ['#c8102e', '#3b1f1a', '#fff1e0'],
    ...pass('common'),
  },
  {
    id: 'color.marshmallow',
    slot: 'color',
    name: 'Marshmallow Puff',
    description: 'Soft, squishy and toasted to nobody.',
    colors: ['#fff8f0', '#ffd6e8', '#c9b8ff'],
    ...pass('common'),
  },
  {
    id: 'color.pistachio',
    slot: 'color',
    name: 'Pistachio Cream',
    description: 'Nutty green gelato with a waffle-cone trim.',
    colors: ['#b5d99c', '#fff4d6', '#8a6b4a'],
    ...pass('common'),
  },
  {
    id: 'color.blue-raspberry',
    slot: 'color',
    name: 'Blue Razz',
    description: 'A flavour that does not exist in nature. Delicious.',
    colors: ['#2f7dff', '#7cf2ff', '#ff3b8d'],
    ...pass('uncommon'),
  },
  {
    id: 'color.peach-ring',
    slot: 'color',
    name: 'Peach Ring',
    description: 'Sugar-dusted peach with a sunny centre.',
    colors: ['#ffb07a', '#ffe08a', '#ff6f61'],
    ...pass('uncommon'),
  },
  {
    id: 'color.caramel-apple',
    slot: 'color',
    name: 'Caramel Apple',
    description: 'Crisp green apple dunked in caramel.',
    colors: ['#7ad151', '#c98a3d', '#5a3b2e'],
    ...pass('uncommon'),
  },
  {
    id: 'color.root-beer',
    slot: 'color',
    name: 'Root Beer Float',
    description: 'Frothy cream on a fizzy brown base.',
    colors: ['#6b3a22', '#fff1d6', '#d98c4a'],
    ...pass('uncommon'),
  },
  {
    id: 'color.sour-apple',
    slot: 'color',
    name: 'Sour Apple Zap',
    description: 'So sour your eyes water from across the course.',
    colors: ['#9dff3b', '#2fbf71', '#fffb8a'],
    ...pass('rare'),
  },
  {
    id: 'color.berry-swirl',
    slot: 'color',
    name: 'Berry Swirl',
    description: 'Raspberry and blackcurrant, swirled not stirred.',
    colors: ['#c2185b', '#7e57c2', '#f8bbd0'],
    ...pass('rare'),
  },
  {
    id: 'color.honeycomb',
    slot: 'color',
    name: 'Honeycomb Crunch',
    description: 'Golden, crackly and full of tiny air pockets.',
    colors: ['#ffb300', '#fff3c4', '#6d4c1f'],
    ...pass('rare'),
  },
  {
    id: 'color.rock-candy',
    slot: 'color',
    name: 'Rock Candy Crystal',
    description: 'Pale crystal facets that catch the stage lights.',
    colors: ['#a0e9ff', '#e0b0ff', '#ffffff'],
    ...pass('epic'),
  },
  {
    id: 'color.chocolate-fudge',
    slot: 'color',
    name: 'Triple Fudge',
    description: 'Three layers of chocolate. Zero regrets.',
    colors: ['#4e2a1e', '#8b5a3c', '#ffd8a8'],
    ...pass('epic'),
  },
  {
    id: 'color.sugar-rush',
    slot: 'color',
    name: 'Sugar Rush',
    description: 'The Season 1 signature: hot pink, electric blue, pure buzz.',
    colors: ['#ff2e93', '#00e0ff', '#ffe600'],
    ...pass('legendary'),
  },
];

const sugarRushPatterns: CosmeticItemInput[] = [
  {
    id: 'pattern.peppermint',
    slot: 'pattern',
    name: 'Peppermint Twist',
    description: 'Chunky stripes wound the other way round.',
    pattern: 'stripes',
    scale: 1.4,
    angle: -35,
    ...pass('common'),
  },
  {
    id: 'pattern.gumball-dots',
    slot: 'pattern',
    name: 'Gumball Machine',
    description: 'Big round gumballs, ready to roll out.',
    pattern: 'dots',
    scale: 0.6,
    ...pass('common'),
  },
  {
    id: 'pattern.ribbon-candy',
    slot: 'pattern',
    name: 'Ribbon Candy',
    description: 'Folded sugar ribbons running head to toe.',
    pattern: 'waves',
    scale: 1.6,
    angle: 90,
    ...pass('common'),
  },
  {
    id: 'pattern.licorice-lace',
    slot: 'pattern',
    name: 'Licorice Lace',
    description: 'Tight zigzag laces of chewy licorice.',
    pattern: 'zigzag',
    scale: 1.5,
    angle: 90,
    ...pass('uncommon'),
  },
  {
    id: 'pattern.jelly-tile',
    slot: 'pattern',
    name: 'Jelly Tiles',
    description: 'Tiny wobbly jelly squares, set on the diagonal.',
    pattern: 'checker',
    scale: 0.5,
    angle: 45,
    ...pass('uncommon'),
  },
  {
    id: 'pattern.cookie-crumble',
    slot: 'pattern',
    name: 'Cookie Crumble',
    description: 'Extra chunky, extra crumbly.',
    pattern: 'spots',
    scale: 1.6,
    ...pass('uncommon'),
  },
  {
    id: 'pattern.taffy-pull',
    slot: 'pattern',
    name: 'Taffy Pull',
    description: 'One giant stretchy swirl, fresh off the hook.',
    pattern: 'swirl',
    scale: 0.6,
    ...pass('rare'),
  },
  {
    id: 'pattern.mini-hearts',
    slot: 'pattern',
    name: 'Candy Hearts',
    description: 'Dozens of tiny hearts with even tinier messages.',
    pattern: 'hearts',
    scale: 1.8,
    angle: 15,
    ...pass('rare'),
  },
  {
    id: 'pattern.wrapper-plaid',
    slot: 'pattern',
    name: 'Wrapper Plaid',
    description: 'Tartan borrowed from a fancy toffee tin.',
    pattern: 'plaid',
    scale: 0.7,
    angle: 45,
    ...pass('rare'),
  },
  {
    id: 'pattern.neapolitan',
    slot: 'pattern',
    name: 'Neapolitan Split',
    description: 'Sliced clean down the middle, ice-cream style.',
    pattern: 'split',
    angle: 90,
    ...pass('epic'),
  },
  {
    id: 'pattern.gemstone',
    slot: 'pattern',
    name: 'Gemstone Glaze',
    description: 'Big glossy facets like a cut sugar jewel.',
    pattern: 'diamonds',
    scale: 1.5,
    ...pass('epic'),
  },
  {
    id: 'pattern.sugar-nebula',
    slot: 'pattern',
    name: 'Sugar Nebula',
    description: 'A sprawling candy galaxy, tilted for drama.',
    pattern: 'galaxy',
    scale: 0.7,
    angle: 30,
    ...pass('legendary'),
  },
];

const sugarRushFaces: CosmeticItemInput[] = [
  {
    id: 'face.gumdrop-gaze',
    slot: 'face',
    name: 'Gumdrop Gaze',
    description: 'Big orange eyes, round as gumdrops.',
    face: { iris: '#ff8a3d', eyeScale: 1.15 },
    ...pass('common'),
  },
  {
    id: 'face.sugar-sleepy',
    slot: 'face',
    name: 'Sugar Crash',
    description: 'What happens ten minutes after the rush.',
    face: { lidRest: 0.25, lashes: true, iris: '#c25bff' },
    ...pass('common'),
  },
  {
    id: 'face.sprinkle-freckles',
    slot: 'face',
    name: 'Sprinkle Cheeks',
    description: 'Freckles like a light dusting of sprinkles.',
    face: { freckles: true, lashes: true, iris: '#3fa9ff' },
    ...pass('uncommon'),
  },
  {
    id: 'face.lemon-squint',
    slot: 'face',
    name: 'Sour Squint',
    description: 'Just bit into a lemon drop. Regrets nothing.',
    face: { lidRest: 0.5, iris: '#ffe14d', blush: false },
    ...pass('uncommon'),
  },
  {
    id: 'face.minty-cat',
    slot: 'face',
    name: 'Minty Glare',
    description: 'Cool cat eyes with a fresh mint shine.',
    face: { pupil: 'cat', iris: '#3fd0a8', lashes: true },
    ...pass('uncommon'),
  },
  {
    id: 'face.candy-specs',
    slot: 'face',
    name: 'Candy Specs',
    description: 'Bubblegum-pink frames for reading the course.',
    face: { accessory: 'glasses', tint: ['#ff4f8b'] },
    ...pass('rare'),
  },
  {
    id: 'face.twirl-stache',
    slot: 'face',
    name: 'Toffee Twirl',
    description: 'A golden toffee mustache, waxed to perfection.',
    face: { accessory: 'mustache', tint: ['#ffcf4a'], eyeScale: 0.9 },
    ...pass('rare'),
  },
  {
    id: 'face.swirl-eyes',
    slot: 'face',
    name: 'Lollipop Hypno',
    description: 'Pink spiral eyes on a frosted face plate.',
    face: { pupil: 'spiral', iris: '#ff2e93', eyeScale: 1.2, plateColor: '#fff0f8' },
    ...pass('epic'),
  },
  {
    id: 'face.racer-visor',
    slot: 'face',
    name: 'Sugar Rush Visor',
    description: 'Orange-tinted racing visor. Eyes on the finish.',
    face: { accessory: 'visor', tint: ['#ff8a3d'], lidRest: 0.15 },
    ...pass('epic'),
  },
  {
    id: 'face.star-gaze',
    slot: 'face',
    name: 'Golden Glimmer',
    description: 'Gold star shades over star-struck eyes.',
    face: { accessory: 'star-shades', tint: ['#ffd23f'], pupil: 'star', iris: '#ffb02e' },
    ...pass('epic'),
  },
];

const sugarRushHeadwear: CosmeticItemInput[] = [
  {
    id: 'headwear.gumdrop-cone',
    slot: 'headwear',
    name: 'Gumdrop Cone',
    description: 'A lime party cone with a sugary tip.',
    mesh: 'party-cone',
    tint: ['#7ad151', '#ffffff', '#ff4f8b'],
    ...pass('common'),
  },
  {
    id: 'headwear.mint-beanie',
    slot: 'headwear',
    name: 'Mint Beanie',
    description: 'Cool mint knit with a snowy pom.',
    mesh: 'beanie-pom',
    tint: ['#7ff0c8', '#ffffff'],
    ...pass('common'),
  },
  {
    id: 'headwear.cherry-sprout',
    slot: 'headwear',
    name: 'Cherry Stem',
    description: 'You are the cherry on top.',
    mesh: 'sprout',
    tint: ['#c8102e'],
    ...pass('common'),
  },
  {
    id: 'headwear.cupcake-chef',
    slot: 'headwear',
    name: 'Cupcake Chef',
    description: 'A frosting-pink chef hat for sweet creations.',
    mesh: 'chef-hat',
    tint: ['#ffc4e8'],
    ...pass('uncommon'),
  },
  {
    id: 'headwear.lolli-propeller',
    slot: 'headwear',
    name: 'Lollicopter',
    description: 'A lollipop-striped whirly cap.',
    mesh: 'propeller-cap',
    tint: ['#ff2e93', '#ffffff', '#7cf2ff'],
    ...pass('uncommon'),
  },
  {
    id: 'headwear.cocoa-ears',
    slot: 'headwear',
    name: 'Cocoa Kitty Ears',
    description: 'Hot-chocolate ears with marshmallow insides.',
    mesh: 'cat-ears',
    tint: ['#6b3a22', '#ffd8a8'],
    ...pass('uncommon'),
  },
  {
    id: 'headwear.jelly-feelers',
    slot: 'headwear',
    name: 'Jelly Feelers',
    description: 'Wobbly antennae tipped with lemon jelly.',
    mesh: 'antenna',
    tint: ['#ff6fb5', '#ffe14d'],
    ...pass('rare'),
  },
  {
    id: 'headwear.marshmallow-bunny',
    slot: 'headwear',
    name: 'Marshmallow Ears',
    description: 'Pillowy ears with a candy-floss lining.',
    mesh: 'bunny-ears',
    tint: ['#fff8f0', '#ff9ef0'],
    ...pass('rare'),
  },
  {
    id: 'headwear.candy-headphones',
    slot: 'headwear',
    name: 'Sweet Beats',
    description: 'Pink-and-aqua cans pumping the Sugar Rush mix.',
    mesh: 'headphones',
    tint: ['#ff4f8b', '#7cf2ff'],
    ...pass('rare'),
  },
  {
    id: 'headwear.licorice-horns',
    slot: 'headwear',
    name: 'Licorice Horns',
    description: 'Glossy black horns with a hot-pink cap.',
    mesh: 'horns',
    tint: ['#2a2238', '#ff2e93'],
    ...pass('epic'),
  },
  {
    id: 'headwear.ringmaster',
    slot: 'headwear',
    name: 'Ringmaster Topper',
    description: 'Cherry-red top hat for running the whole show.',
    mesh: 'top-hat',
    tint: ['#c8102e', '#ffd23f'],
    ...pass('epic'),
  },
  {
    id: 'headwear.sugar-halo',
    slot: 'headwear',
    name: 'Spun Sugar Halo',
    description: 'A glowing ring of pink candy floss.',
    mesh: 'halo',
    tint: ['#ff9ef0'],
    ...pass('legendary'),
  },
];

const sugarRushBack: CosmeticItemInput[] = [
  {
    id: 'back.lunchbox',
    slot: 'back',
    name: 'Lunchbox Pack',
    description: 'Packed with sandwiches. Mostly candy sandwiches.',
    mesh: 'backpack',
    tint: ['#ff8a3d', '#7ff0c8'],
    ...pass('common'),
  },
  {
    id: 'back.gummy-shell',
    slot: 'back',
    name: 'Gummy Shell',
    description: 'A chewy shell in strawberry and lemon.',
    mesh: 'shell',
    tint: ['#ff5a6e', '#ffe14d'],
    ...pass('uncommon'),
  },
  {
    id: 'back.taffy-tail',
    slot: 'back',
    name: 'Taffy Tail',
    description: 'A stretchy striped tail that never stops wagging.',
    mesh: 'tail',
    tint: ['#ffb3d9', '#7ff0c8'],
    ...pass('uncommon'),
  },
  {
    id: 'back.wrapper-cape',
    slot: 'back',
    name: 'Wrapper Cape',
    description: 'A crinkly sweet-wrapper cape in blue and pink.',
    mesh: 'cape',
    tint: ['#3fa9ff', '#ff4f8b'],
    ...pass('rare'),
  },
  {
    id: 'back.fizz-rockets',
    slot: 'back',
    name: 'Fizz Rockets',
    description: 'Soda-powered boosters. Shake before use.',
    mesh: 'jetpack',
    tint: ['#ff2e93', '#7cf2ff'],
    ...pass('rare'),
  },
  {
    id: 'back.butterscotch-wings',
    slot: 'back',
    name: 'Butterscotch Wings',
    description: 'Golden wings of brittle, glowing butterscotch.',
    mesh: 'wings',
    tint: ['#ffcf4a', '#fff3c4'],
    ...pass('epic'),
  },
  {
    id: 'back.cotton-candy-wings',
    slot: 'back',
    name: 'Cotton Candy Wings',
    description: 'Fluffy pink-and-blue wings spun at the fair.',
    mesh: 'wings',
    tint: ['#ff9ef0', '#a0e9ff'],
    ...pass('legendary'),
  },
];

const sugarRushUpper: CosmeticItemInput[] = [
  {
    id: 'upper.licorice-bow',
    slot: 'upper',
    name: 'Licorice Bow',
    description: 'A smart black bow tie, faintly aniseed.',
    mesh: 'bow-tie',
    tint: ['#2a2238'],
    ...pass('common'),
  },
  {
    id: 'upper.lemon-bow',
    slot: 'upper',
    name: 'Lemon Drop Bow',
    description: 'A sunny yellow bow with a zesty edge.',
    mesh: 'bow-tie',
    tint: ['#ffe14d', '#ff8a3d'],
    ...pass('common'),
  },
  {
    id: 'upper.peppermint-scarf',
    slot: 'upper',
    name: 'Peppermint Scarf',
    description: 'Red-and-white stripes that flap at full sprint.',
    mesh: 'scarf',
    tint: ['#ffffff', '#e53935'],
    ...pass('uncommon'),
  },
  {
    id: 'upper.gumball-medal',
    slot: 'upper',
    name: 'Silver Gumball Medal',
    description: 'Second place never tasted so sweet.',
    mesh: 'medal',
    tint: ['#c0c8d8', '#ff4f8b'],
    ...pass('uncommon'),
  },
  {
    id: 'upper.mint-scarf',
    slot: 'upper',
    name: 'Mint Chip Muffler',
    description: 'Mint knit with chocolate-chip flecks.',
    mesh: 'scarf',
    tint: ['#7ff0c8', '#5a3b2e'],
    ...pass('rare'),
  },
  {
    id: 'upper.gold-medal',
    slot: 'upper',
    name: 'Golden Gobstopper Medal',
    description: 'Awarded for surviving every round of the season.',
    mesh: 'medal',
    tint: ['#ffcf4a', '#c8102e'],
    ...pass('rare'),
  },
  {
    id: 'upper.rush-medal',
    slot: 'upper',
    name: 'Sugar Rush Medal',
    description: 'The official Season 1 medal, still sticky.',
    mesh: 'medal',
    tint: ['#ff2e93', '#00e0ff'],
    ...pass('epic'),
  },
];

const sugarRushLower: CosmeticItemInput[] = [
  {
    id: 'lower.candy-belt',
    slot: 'lower',
    name: 'Candy Cane Belt',
    description: 'A striped belt with a minty buckle.',
    mesh: 'belt',
    tint: ['#ff4f8b', '#ffffff'],
    ...pass('common'),
  },
  {
    id: 'lower.racer-shorts',
    slot: 'lower',
    name: 'Racer Shorts',
    description: 'Orange go-faster stripes on midnight shorts.',
    mesh: 'shorts-stripes',
    tint: ['#ff8a3d', '#2a2238'],
    ...pass('common'),
  },
  {
    id: 'lower.gummy-ring',
    slot: 'lower',
    name: 'Gummy Ring Floatie',
    description: 'An apple gummy ring, inflated for safety.',
    mesh: 'floatie',
    tint: ['#7ad151', '#ffffff'],
    ...pass('uncommon'),
  },
  {
    id: 'lower.lavender-tutu',
    slot: 'lower',
    name: 'Lavender Tutu',
    description: 'A soft lilac tutu that smells faintly of fudge.',
    mesh: 'tutu',
    tint: ['#c9b8ff'],
    ...pass('uncommon'),
  },
  {
    id: 'lower.toffee-belt',
    slot: 'lower',
    name: 'Toffee Champion Belt',
    description: 'A toffee strap with a buckle of solid butterscotch.',
    mesh: 'belt',
    tint: ['#8b5a3c', '#ffd23f'],
    ...pass('rare'),
  },
  {
    id: 'lower.sherbet-tutu',
    slot: 'lower',
    name: 'Sherbet Swirl Tutu',
    description: 'Layers of fizzy sherbet tulle in peach and pink.',
    mesh: 'tutu',
    tint: ['#ff8fb1', '#ffd36e'],
    ...pass('epic'),
  },
];

const sugarRushClips: CosmeticItemInput[] = [
  {
    id: 'emote.sugar-wave',
    slot: 'emote',
    name: 'Sticky Wave',
    description: 'A wave so sweet your hand sticks a little.',
    clip: 'wave',
    ...pass('common'),
  },
  {
    id: 'emote.giggle',
    slot: 'emote',
    name: 'Giggle Fit',
    description: 'Cannot. Stop. Giggling.',
    clip: 'laugh',
    ...pass('common'),
  },
  {
    id: 'emote.sugar-shimmy',
    slot: 'emote',
    name: 'Sugar Shimmy',
    description: 'Too much candy, not enough places to put the energy.',
    clip: 'dance',
    ...pass('common'),
  },
  {
    id: 'emote.stretch',
    slot: 'emote',
    name: 'Pre-Race Stretch',
    description: 'Limber up before the gates drop.',
    clip: 'jumping-jacks',
    ...pass('uncommon'),
  },
  {
    id: 'emote.oops',
    slot: 'emote',
    name: 'Sticky Situation',
    description: 'When you dove straight into the goo. Again.',
    clip: 'facepalm',
    ...pass('uncommon'),
  },
  {
    id: 'emote.who-knows',
    slot: 'emote',
    name: 'Out of Gumballs',
    description: 'Empty pockets, zero worries.',
    clip: 'shrug',
    ...pass('uncommon'),
  },
  {
    id: 'emote.lollipop-spin',
    slot: 'emote',
    name: 'Lollipop Spin',
    description: 'Twirl like a lolly on a stick.',
    clip: 'spin',
    ...pass('rare'),
  },
  {
    id: 'emote.curtsy',
    slot: 'emote',
    name: 'Sweet Curtsy',
    description: 'A polite little bow for good sports.',
    clip: 'bow',
    ...pass('rare'),
  },
  {
    id: 'emote.cheer-squad',
    slot: 'emote',
    name: 'Cheer Squad',
    description: 'Rally the team, pom-poms optional.',
    clip: 'cheer',
    ...pass('epic'),
  },
  {
    id: 'celebration.hop-hop',
    slot: 'celebration',
    name: 'Sugar Hop',
    description: 'Bounce, bounce, bounce across the line.',
    clip: 'jumping-jacks',
    ...pass('common'),
  },
  {
    id: 'celebration.wiggle',
    slot: 'celebration',
    name: 'Finish Line Wiggle',
    description: 'Qualified! Time to wiggle.',
    clip: 'dance',
    ...pass('uncommon'),
  },
  {
    id: 'celebration.pump',
    slot: 'celebration',
    name: 'Gumball Pump',
    description: 'Pump it like a gumball machine handle.',
    clip: 'fist-pump',
    ...pass('uncommon'),
  },
  {
    id: 'celebration.twirl',
    slot: 'celebration',
    name: 'Cotton Candy Twirl',
    description: 'Spin until you are fluffy.',
    clip: 'spin',
    ...pass('rare'),
  },
  {
    id: 'celebration.giddy',
    slot: 'celebration',
    name: 'Giddy Giggles',
    description: 'Laughing all the way to the next round.',
    clip: 'laugh',
    ...pass('rare'),
  },
  {
    id: 'celebration.flex',
    slot: 'celebration',
    name: 'Jawbreaker Flex',
    description: 'Rock-hard candy muscles on full display.',
    clip: 'flex',
    ...pass('epic'),
  },
  {
    id: 'celebration.flip',
    slot: 'celebration',
    name: 'Sprinkle Flip',
    description: 'A backflip that leaves sprinkles hanging in the air.',
    clip: 'backflip',
    ...pass('epic'),
  },
  {
    id: 'victory.encore-bow',
    slot: 'victory',
    name: 'Encore Bow',
    description: 'A deep bow while the crowd chants for more.',
    clip: 'bow',
    ...pass('rare'),
  },
  {
    id: 'victory.cheer',
    slot: 'victory',
    name: 'Confetti Cheer',
    description: 'Leap for joy under a confetti cannon.',
    clip: 'cheer',
    ...pass('epic'),
  },
  {
    id: 'victory.hero-gold',
    slot: 'victory',
    name: 'Candy Champion',
    description: 'A heroic stance atop a mountain of sweets.',
    clip: 'victory-hero',
    ...pass('legendary'),
  },
  {
    id: 'victory.sugar-rush',
    slot: 'victory',
    name: 'Sugar Rush Supreme',
    description: 'The Season 1 finale pose. Arms up, sugar high, crown secured.',
    clip: 'victory-superstar',
    ...pass('mythic'),
  },
];

const sugarRushProfile: CosmeticItemInput[] = [
  {
    id: 'nameplate.lemon-pill',
    slot: 'nameplate',
    name: 'Lemon Pill',
    description: 'Sunny yellow with a tangy orange rim.',
    plate: { style: 'pill', bg: '#ffe14d', bg2: '#fff19a', text: '#5a3b2e', border: '#ff8a3d' },
    ...pass('common'),
  },
  {
    id: 'nameplate.grape-bubble',
    slot: 'nameplate',
    name: 'Grape Bubble',
    description: 'A purple bubble that never pops.',
    plate: { style: 'bubble', bg: '#9b5cff', bg2: '#c9a8ff', text: '#ffffff', border: '#ece0ff' },
    ...pass('common'),
  },
  {
    id: 'nameplate.cola-ticket',
    slot: 'nameplate',
    name: 'Cola Ticket',
    description: 'A fizzy brown ticket stub.',
    plate: { style: 'ticket', bg: '#6b3a22', bg2: '#8b5a3c', text: '#fff1d6', border: '#d98c4a' },
    ...pass('common'),
  },
  {
    id: 'nameplate.taffy-ribbon',
    slot: 'nameplate',
    name: 'Taffy Ribbon',
    description: 'Pink taffy ribbon with a mint edge.',
    plate: { style: 'ribbon', bg: '#ffb3d9', bg2: '#ffd6ec', text: '#7a2d55', border: '#7ff0c8' },
    ...pass('uncommon'),
  },
  {
    id: 'nameplate.mint-bubble',
    slot: 'nameplate',
    name: 'Mint Fizz',
    description: 'A cool, bubbly mint plate.',
    plate: { style: 'bubble', bg: '#3fd0a8', bg2: '#9ff5d9', text: '#1e3b33', border: '#ffffff' },
    ...pass('uncommon'),
  },
  {
    id: 'nameplate.cherry-pill',
    slot: 'nameplate',
    name: 'Cherry Pop',
    description: 'Glossy cherry red with a golden glint.',
    plate: { style: 'pill', bg: '#c8102e', bg2: '#ff4f6a', text: '#ffffff', border: '#ffd23f' },
    ...pass('uncommon'),
  },
  {
    id: 'nameplate.golden-ticket',
    slot: 'nameplate',
    name: 'Gold Wrapper',
    description: 'Found inside the very last chocolate bar.',
    plate: { style: 'ticket', bg: '#ffcf4a', bg2: '#fff3a0', text: '#6d4c1f', border: '#c8102e' },
    ...pass('rare'),
  },
  {
    id: 'nameplate.sour-neon',
    slot: 'nameplate',
    name: 'Sour Neon',
    description: 'Buzzing lime neon. Tastes like a battery.',
    plate: { style: 'neon', bg: '#14261a', bg2: '#1f3a26', text: '#b6ff3b', border: '#ffe600' },
    ...pass('rare'),
  },
  {
    id: 'nameplate.sugar-rush',
    slot: 'nameplate',
    name: 'Sugar Rush Sign',
    description: 'The Season 1 marquee in pink and electric blue.',
    plate: { style: 'neon', bg: '#2a0f2e', bg2: '#3d1442', text: '#ff9ef0', border: '#00e0ff' },
    ...pass('epic'),
  },
  {
    id: 'banner.lemonade',
    slot: 'banner',
    name: 'Lemonade Stand',
    description: 'Fresh-squeezed stripes, five gumballs a cup.',
    banner: { motif: 'stripes', colors: ['#ffe14d', '#ffffff', '#ff8a3d'] },
    ...pass('common'),
  },
  {
    id: 'banner.cotton-sky',
    slot: 'banner',
    name: 'Cotton Candy Sky',
    description: 'Pastel clouds you could almost eat.',
    banner: { motif: 'clouds', colors: ['#ffc4e8', '#b8e7ff', '#ffffff'] },
    ...pass('common'),
  },
  {
    id: 'banner.sprinkle-party',
    slot: 'banner',
    name: 'Sprinkle Party',
    description: 'Vanilla frosting with a fistful of sprinkles.',
    banner: { motif: 'confetti', colors: ['#fff8f0', '#ff4f8b', '#3fa9ff'] },
    ...pass('common'),
  },
  {
    id: 'banner.soda-waves',
    slot: 'banner',
    name: 'Soda Fountain',
    description: 'Rolling waves of root beer and cream.',
    banner: { motif: 'waves', colors: ['#6b3a22', '#d98c4a', '#fff1d6'] },
    ...pass('uncommon'),
  },
  {
    id: 'banner.gumball-machine',
    slot: 'banner',
    name: 'Gumball Bonanza',
    description: 'Red, yellow and blue gumballs everywhere.',
    banner: { motif: 'candy', colors: ['#e53935', '#ffd23f', '#3fa9ff'] },
    ...pass('uncommon'),
  },
  {
    id: 'banner.mint-stripes',
    slot: 'banner',
    name: 'Mint Racer',
    description: 'Cool mint racing stripes.',
    banner: { motif: 'stripes', colors: ['#7ff0c8', '#ffffff', '#2fbf71'] },
    ...pass('uncommon'),
  },
  {
    id: 'banner.night-market',
    slot: 'banner',
    name: 'Midnight Sweets',
    description: 'A late-night candy market under neon stars.',
    banner: { motif: 'stars', colors: ['#2a0f2e', '#ff2e93', '#7cf2ff'] },
    ...pass('rare'),
  },
  {
    id: 'banner.lollipop-land',
    slot: 'banner',
    name: 'Lollipop Land',
    description: 'Lollipops as far as the eye can see.',
    banner: { motif: 'candy', colors: ['#ff9ef0', '#ffe600', '#7ad151'] },
    ...pass('rare'),
  },
  {
    id: 'banner.sugar-rush',
    slot: 'banner',
    name: 'Sugar Rush Spectacular',
    description: 'The full Season 1 confetti blast.',
    banner: { motif: 'confetti', colors: ['#ff2e93', '#00e0ff', '#ffe600'] },
    ...pass('epic'),
  },
];

const sugarRushVfx: CosmeticItemInput[] = [
  {
    id: 'trail.fizz',
    slot: 'trail',
    name: 'Soda Fizz',
    description: 'Creamy soda bubbles trail behind you.',
    trail: { kind: 'bubbles', colors: ['#ffd8a8', '#fff1d6'] },
    ...pass('common'),
  },
  {
    id: 'trail.sugar-sparkle',
    slot: 'trail',
    name: 'Sugar Glitter',
    description: 'A fine dusting of pink sugar.',
    trail: { kind: 'sparkle', colors: ['#ff9ef0', '#ffffff'] },
    ...pass('common'),
  },
  {
    id: 'trail.candy-hearts',
    slot: 'trail',
    name: 'Lemon Hearts',
    description: 'Citrus hearts bobbing in your wake.',
    trail: { kind: 'hearts', colors: ['#ffe14d', '#ff8a3d'] },
    ...pass('uncommon'),
  },
  {
    id: 'trail.sprinkles',
    slot: 'trail',
    name: 'Sprinkle Shake',
    description: 'Leaves a sprinkle mess everywhere you go.',
    trail: { kind: 'confetti', colors: ['#ff4f8b', '#3fa9ff', '#ffe14d'] },
    ...pass('uncommon'),
  },
  {
    id: 'trail.mint-stars',
    slot: 'trail',
    name: 'Mint Meteor',
    description: 'Cool mint stars streaking behind you.',
    trail: { kind: 'stars', colors: ['#7ff0c8', '#ffffff'] },
    ...pass('rare'),
  },
  {
    id: 'trail.taffy-rainbow',
    slot: 'trail',
    name: 'Pastel Ribbon',
    description: 'A soft pastel rainbow, stretched like taffy.',
    trail: { kind: 'rainbow', colors: ['#ff9ef0', '#ffd36e', '#7ff0c8', '#c9b8ff'] },
    ...pass('epic'),
  },
  {
    id: 'trail.sugar-streak',
    slot: 'trail',
    name: 'Sugar Rush Streak',
    description: 'A blazing neon streak. The rush made visible.',
    trail: { kind: 'rainbow', colors: ['#ff2e93', '#ffe600', '#00e0ff', '#b6ff3b'] },
    ...pass('legendary'),
  },
  {
    id: 'footsteps.gummy-squeak',
    slot: 'footsteps',
    name: 'Gummy Squeaks',
    description: 'Squeaky gummy soles.',
    pack: 'squeak',
    ...pass('common'),
  },
  {
    id: 'footsteps.marshmallow',
    slot: 'footsteps',
    name: 'Marshmallow Stomp',
    description: 'Soft, squishy, oddly satisfying steps.',
    pack: 'jelly',
    ...pass('common'),
  },
  {
    id: 'footsteps.pogo',
    slot: 'footsteps',
    name: 'Pogo Pops',
    description: 'Every step a little bounce.',
    pack: 'boing',
    ...pass('uncommon'),
  },
  {
    id: 'footsteps.candy-tap',
    slot: 'footsteps',
    name: 'Candy Clickers',
    description: 'Hard-candy heels that click on every tile.',
    pack: 'tap',
    ...pass('uncommon'),
  },
  {
    id: 'footsteps.sleigh-bells',
    slot: 'footsteps',
    name: 'Sleigh Bell Sprint',
    description: 'A jingle on every stride, all season long.',
    pack: 'bell',
    ...pass('rare'),
  },
];

// -----------------------------------------------------------------------------
// Catalog
// -----------------------------------------------------------------------------

/** Every launch cosmetic, validated. */
export const COSMETICS: readonly CosmeticItem[] = [
  ...colors,
  ...patterns,
  ...faces,
  ...headwear,
  ...back,
  ...upper,
  ...lower,
  ...emotes,
  ...celebrations,
  ...victories,
  ...nameplates,
  ...banners,
  ...trails,
  ...footsteps,
  ...sugarRushColors,
  ...sugarRushPatterns,
  ...sugarRushFaces,
  ...sugarRushHeadwear,
  ...sugarRushBack,
  ...sugarRushUpper,
  ...sugarRushLower,
  ...sugarRushClips,
  ...sugarRushProfile,
  ...sugarRushVfx,
].map((item) => CosmeticItemSchema.parse(item));

const byId = new Map<string, CosmeticItem>();
for (const item of COSMETICS) {
  if (byId.has(item.id)) throw new Error(`Duplicate cosmetic id: ${item.id}`);
  byId.set(item.id, item);
}

/**
 * Looks up a cosmetic by id.
 *
 * @param id - Cosmetic id.
 * @returns The item, or `undefined` when unknown.
 */
export function getCosmetic(id: string): CosmeticItem | undefined {
  return byId.get(id);
}

/**
 * The item type stored in slot `S`. Distributes over the item union because
 * accessory items share one schema across four slots.
 */
export type ItemOfSlot<S extends CosmeticSlot> = CosmeticItem extends infer T
  ? T extends { slot: infer U }
    ? S extends U
      ? T & { slot: S }
      : never
    : never
  : never;

/**
 * Looks up a cosmetic by id and checks its slot.
 *
 * @param id - Cosmetic id.
 * @param slot - Expected slot.
 * @returns The typed item, or `undefined` when unknown or in another slot.
 * @example
 * const hat = getCosmeticInSlot('headwear.halo', 'headwear');
 */
export function getCosmeticInSlot<S extends CosmeticSlot>(id: string, slot: S): ItemOfSlot<S> | undefined {
  const item = byId.get(id);
  return item && item.slot === slot ? (item as ItemOfSlot<S>) : undefined;
}

/**
 * Lists every item in a slot, sorted by rarity then name.
 *
 * @param slot - The slot to list.
 * @returns A new array of items.
 */
export function cosmeticsInSlot<S extends CosmeticSlot>(slot: S): ItemOfSlot<S>[] {
  const order = ['common', 'uncommon', 'rare', 'epic', 'legendary', 'mythic'];
  return COSMETICS.filter((c) => c.slot === slot)
    .sort((a, b) => order.indexOf(a.rarity) - order.indexOf(b.rarity) || a.name.localeCompare(b.name))
    .map((c) => c as ItemOfSlot<S>);
}
